package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.domain.matchcollect.MatchCollectStatus
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.FixtureMatchCollectState
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class FixtureMatchCollectStateRepositoryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @Autowired
    private lateinit var stateRepository: FixtureMatchCollectStateRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `fixture 하나당 match collect state는 하나만 저장된다`() {
        val fixture = saveFixture("fixture-state-unique")
        stateRepository.save(FixtureMatchCollectState(fixture = fixture))

        assertThatThrownBy {
            stateRepository.save(FixtureMatchCollectState(fixture = fixture))
        }.isInstanceOf(DataIntegrityViolationException::class.java)
    }

    @Test
    fun `fixture uid로 state를 조회한다`() {
        val fixture = saveFixture("fixture-state-find")
        stateRepository.save(
            FixtureMatchCollectState(
                fixture = fixture,
                matchCollectStatus = MatchCollectStatus.EARLY_SYNCED,
            ),
        )
        em.flush()
        em.clear()

        val found = stateRepository.findByFixture_Uid(fixture.uid)

        assertThat(found).isNotNull
        assertThat(found?.fixture?.uid).isEqualTo(fixture.uid)
        assertThat(found?.matchCollectStatus).isEqualTo(MatchCollectStatus.EARLY_SYNCED)
    }

    @Test
    fun `lastCollectedAt을 저장한다`() {
        val fixture = saveFixture("fixture-last-collected")
        val lastCollectedAt = Instant.parse("2026-06-15T12:00:00Z")
        stateRepository.save(
            FixtureMatchCollectState(
                fixture = fixture,
                lastCollectedAt = lastCollectedAt,
            ),
        )
        em.flush()
        em.clear()

        val found = stateRepository.findByFixture_Uid(fixture.uid)

        assertThat(found?.lastCollectedAt).isEqualTo(lastCollectedAt)
    }

    private fun saveFixture(
        uid: String,
        kickoff: Instant = Instant.parse("2026-06-15T09:00:00Z"),
        fixtureAvailable: Boolean = false,
        leagueAvailable: Boolean = true,
        matchCollect: MatchCollect = MatchCollect.FINISHED,
    ): FixtureCore {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-$uid",
                    name = "League $uid",
                    available = leagueAvailable,
                    matchCollect = matchCollect,
                    autoGenerated = false,
                ),
            )
        return fixtureCoreRepository.save(
            FixtureCore(
                uid = uid,
                kickoff = kickoff,
                statusText = "Not Started",
                statusCode = FixtureStatusCode.NS,
                league = league,
                homeTeam = null,
                awayTeam = null,
                available = fixtureAvailable,
                autoGenerated = false,
            ),
        )
    }
}
