package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.domain.matchcollect.MatchCollectStatus
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.FixtureMatchCollectState
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.data.domain.PageRequest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class FixtureCoreMatchCollectLiveJobRepositoryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @Autowired
    private lateinit var fixtureCoreRepository: FixtureCoreRepository

    @Autowired
    private lateinit var fixtureMatchCollectStateRepository: FixtureMatchCollectStateRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `live job reconcile fixture 조회는 current season의 unavailable fixture만 가져오고 matchCollect 값으로 필터링하지 않는다`() {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-live-reconcile",
                    name = "League Live Reconcile",
                    available = true,
                    matchCollect = MatchCollect.NONE,
                    autoGenerated = false,
                ),
            )
        val currentSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2026,
                    current = true,
                    autoGenerated = false,
                ),
            )
        val oldSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2025,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val currentFixture = saveFixture("fixture-current", league, currentSeason)
        saveFixture("fixture-old", league, oldSeason)
        saveFixture("fixture-available", league, currentSeason, available = true)
        em.flush()
        em.clear()

        val result = fixtureCoreRepository.findMatchCollectLiveJobReconcileFixturesByLeagueUid(league.uid)

        assertThat(result.map { it.uid }).containsExactly(currentFixture.uid)
        assertThat(result.first().leagueSeason?.current).isTrue()
        assertThat(result.first().leagueSeason?.league?.matchCollect).isEqualTo(MatchCollect.NONE)
    }

    @Test
    fun `admin league match collect fixture 조회는 current season unavailable fixture를 state 유무와 함께 가져온다`() {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-admin-match-collect-fixtures",
                    name = "League Admin Match Collect Fixtures",
                    available = true,
                    matchCollect = MatchCollect.LIVE,
                    autoGenerated = false,
                ),
            )
        val currentSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2026,
                    current = true,
                    autoGenerated = false,
                ),
            )
        val oldSeason =
            leagueSeasonCoreRepository.save(
                LeagueSeasonCore(
                    league = league,
                    seasonYear = 2025,
                    current = false,
                    autoGenerated = false,
                ),
            )
        val synced = saveFixture("fixture-admin-synced", league, currentSeason)
        val withoutState = saveFixture("fixture-admin-without-state", league, currentSeason)
        val incomplete = saveFixture("fixture-admin-incomplete", league, currentSeason)
        saveFixture("fixture-admin-available", league, currentSeason, available = true)
        saveFixture("fixture-admin-old", league, oldSeason)
        fixtureMatchCollectStateRepository.save(
            FixtureMatchCollectState(
                fixture = synced,
                matchCollectStatus = MatchCollectStatus.EARLY_SYNCED,
            ),
        )
        fixtureMatchCollectStateRepository.save(
            FixtureMatchCollectState(
                fixture = incomplete,
                matchCollectStatus = MatchCollectStatus.DATA_INCOMPLETE_NEEDS_ADMIN,
            ),
        )
        em.flush()
        em.clear()

        val result =
            fixtureCoreRepository.findAdminMatchCollectLeagueFixtures(
                leagueUid = league.uid,
                fixtureUid = null,
                status = null,
                incompleteOnly = false,
                pageable = PageRequest.of(0, 20),
            )

        assertThat(result.content.map { it.uid })
            .containsExactly(synced.uid, withoutState.uid, incomplete.uid)
        assertThat(result.content.map { it.matchCollectState?.matchCollectStatus })
            .containsExactly(MatchCollectStatus.EARLY_SYNCED, null, MatchCollectStatus.DATA_INCOMPLETE_NEEDS_ADMIN)

        val incompleteOnly =
            fixtureCoreRepository.findAdminMatchCollectLeagueFixtures(
                leagueUid = league.uid,
                fixtureUid = null,
                status = null,
                incompleteOnly = true,
                pageable = PageRequest.of(0, 20),
            )

        assertThat(incompleteOnly.content.map { it.uid }).containsExactly(incomplete.uid)
    }

    private fun saveFixture(
        uid: String,
        league: LeagueCore,
        season: LeagueSeasonCore,
        available: Boolean = false,
    ): FixtureCore =
        fixtureCoreRepository.save(
            FixtureCore(
                uid = uid,
                kickoff = Instant.parse("2026-06-15T09:00:00Z"),
                statusText = FixtureStatusCode.NS.code,
                statusCode = FixtureStatusCode.NS,
                league = league,
                leagueSeason = season,
                homeTeam = null,
                awayTeam = null,
                available = available,
                autoGenerated = false,
            ),
        )
}
