package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class LeagueCoreRepositoryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `matchCollect 기본값은 NONE 이다`() {
        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = "league-default-match-collect",
                    name = "Default Match Collect League",
                    available = true,
                    autoGenerated = false,
                ),
            )

        em.flush()
        em.clear()

        val found = leagueCoreRepository.findByUid(league.uid)

        assertThat(found?.matchCollect).isEqualTo(MatchCollect.NONE)
    }

    @Test
    fun `available true 이면서 matchCollect 가 일치하는 리그만 조회한다`() {
        val finishedAvailable =
            createLeague("finished-available", available = true, matchCollect = MatchCollect.FINISHED)
        val finishedUnavailable =
            createLeague("finished-unavailable", available = false, matchCollect = MatchCollect.FINISHED)
        val liveAvailable =
            createLeague("live-available", available = true, matchCollect = MatchCollect.LIVE)

        leagueCoreRepository.saveAll(listOf(finishedAvailable, finishedUnavailable, liveAvailable))
        em.flush()
        em.clear()

        val result = leagueCoreRepository.findByAvailableTrueAndMatchCollect(MatchCollect.FINISHED)

        assertThat(result.map { it.uid }).containsExactly("finished-available")
    }

    private fun createLeague(
        uid: String,
        available: Boolean,
        matchCollect: MatchCollect,
    ): LeagueCore =
        LeagueCore(
            uid = uid,
            name = uid,
            available = available,
            matchCollect = matchCollect,
            autoGenerated = false,
        )
}
