package com.footballay.core.infra.persistence.core.repository

import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.api.Assertions.assertThatThrownBy
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.dao.DataIntegrityViolationException
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.LocalDate

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class LeagueSeasonCoreRepositoryTest {
    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueSeasonCoreRepository: LeagueSeasonCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `리그와 시즌 연도로 season core 를 조회한다`() {
        val league = saveLeague("premier-league")
        leagueSeasonCoreRepository.save(
            LeagueSeasonCore(
                league = league,
                seasonYear = 2025,
                seasonStart = LocalDate.parse("2025-08-01"),
                seasonEnd = LocalDate.parse("2026-05-31"),
                current = true,
                autoGenerated = false,
            ),
        )
        em.flush()
        em.clear()

        val found = leagueSeasonCoreRepository.findByLeagueAndSeasonYear(league, 2025)

        assertThat(found).isNotNull
        assertThat(found?.league?.id).isEqualTo(league.id)
        assertThat(found?.seasonYear).isEqualTo(2025)
        assertThat(found?.seasonStart).isEqualTo(LocalDate.parse("2025-08-01"))
        assertThat(found?.seasonEnd).isEqualTo(LocalDate.parse("2026-05-31"))
        assertThat(found?.current).isTrue()
        assertThat(found?.autoGenerated).isFalse()
    }

    @Test
    fun `같은 리그와 시즌 연도는 중복 저장할 수 없다`() {
        val league = saveLeague("duplicate-season-league")
        leagueSeasonCoreRepository.save(LeagueSeasonCore(league = league, seasonYear = 2025))

        assertThatThrownBy {
            leagueSeasonCoreRepository.save(LeagueSeasonCore(league = league, seasonYear = 2025))
            em.flush()
        }.isInstanceOf(DataIntegrityViolationException::class.java)
    }

    @Test
    fun `current true 인 season core 를 리그 기준으로 조회한다`() {
        val league = saveLeague("current-season-league")
        val otherLeague = saveLeague("other-current-season-league")
        leagueSeasonCoreRepository.saveAll(
            listOf(
                LeagueSeasonCore(league = league, seasonYear = 2024, current = false),
                LeagueSeasonCore(league = league, seasonYear = 2025, current = true),
                LeagueSeasonCore(league = otherLeague, seasonYear = 2025, current = true),
            ),
        )
        em.flush()
        em.clear()

        val result = leagueSeasonCoreRepository.findByLeagueAndCurrentTrue(league)

        assertThat(result.map { it.seasonYear }).containsExactly(2025)
    }

    private fun saveLeague(uid: String): LeagueCore =
        leagueCoreRepository.save(
            LeagueCore(
                uid = uid,
                name = uid,
                autoGenerated = false,
            ),
        )
}
