aws:
  cloudfront:
    domain: "https://static.gyechunhoe.com"
    keyPairId: "MOCKKEYPAIRID"
    privateKeyPath: classpath:MOCKPATHTHISISNOTREAL
    publicKeyPath: classpath:MOCKPATHTHISISNOTREAL

  s3:
    accessKey: AMOCKACCESSKEYZ
    secretKey: XAMOCKSECRETKEYZ
    region: ap-northeast-2
    bucket-name: MOCK-BUCKET-NAME
    public-domain: "https://static.MOCKDOMAINqk20ejkt01ke03.com"