spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  #    show-sql: true

  devtools:
    restart:
      enabled: false
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: FootballayScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
server:
  port: 8083
  ssl:
    client-auth: none
    key-store: classpath:keystore.p12
    key-store-password: -wva9.ea7)}}
    key-store-type: PKCS12
    key-alias: scoreboarddev
    enabled: true

  # monitoring 을 위한 tomcat metrics 활성화 설정
  tomcat:
    mbeanregistry:
      enabled: true
    threads:
      max: 80

# monitoring - actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    root: info
    org:
      testcontainers: debug

# 개발 환경에서 허용할 CORS 출처
cors:
  allowedorigins: "http://localhost:8080,http://localhost:1212,https://localhost:7777,https://localhost:1212,https://localhost:8080,http://localhost:8083,https://localhost:8083,https://static.gyechune.com,https://gyechune.com,https://gyechunhoe.com,https://static.gyechunhoe.com"

custom:
  login:
    remember-me-key: remember-me-key-only-for-dev
