spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/footballay
    username: dev
    password: dev1234
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10   # 기본 값 10
      connection-timeout: 30000
