package com.footballay.core.infra.persistence.core.entity

import com.footballay.core.infra.persistence.apisports.entity.FixtureApiSports
import jakarta.persistence.*
import org.hibernate.proxy.HibernateProxy
import java.time.Instant

/**
 * 공통 Fixture 엔티티입니다. <br>
 * 절대로 API 별 상세 데이터를 담으면 안됩니다. <br>
 *
 */
@Entity
@Table(name = "fixture_core")
data class FixtureCore(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,
    /**
     * 외부 노출 ID
     */
    @Column(name = "uid", unique = true, nullable = false, updatable = false)
    var uid: String,
    /**
     * 경기 시작 시간
     *
     * **Important**: 이 값은 항상 **UTC**로 저장됩니다.
     * - API 응답에서 받은 OffsetDateTime(시간대 정보 포함)을 Instant로 변환하여 UTC 기준으로 저장
     * - 데이터베이스에는 timestamp with time zone 타입으로 UTC 값이 저장됨
     * - 일정이 미정인 경우 null로 처리
     *
     * 조회 시 서비스에서 적절히 지역 시간대로 변환하여 API 응답에 제공해야 합니다.
     *
     * **Note**: kickoff time이 변경된다면, Data Provider의 match data polling 작업을 확인하고 수정 필요
     */
    @Column(columnDefinition = "TIMESTAMP WITH TIME ZONE")
    var kickoff: Instant?,
    /**
     * 경기 상태 (예: Not Started, Full Time, First Half, Half Time, Second Half 등)
     */
    var statusText: String,
    /**
     * 경기 상태 약어 (예: NS, FT, 1H, HT, 2H 등)
     */
    @Enumerated(EnumType.STRING)
    var statusCode: FixtureStatusCode,
    /**
     * 경기 시간 (분 단위)
     * 예: 90, 45, 30 등
     */
    var elapsedMin: Int? = null,
    @ManyToOne(fetch = FetchType.LAZY)
    var league: LeagueCore,
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    var homeTeam: TeamCore?,
    @ManyToOne(fetch = FetchType.LAZY, optional = true)
    var awayTeam: TeamCore?,
    var goalsHome: Int? = null,
    var goalsAway: Int? = null,
    @Column(nullable = false)
    var finished: Boolean = false,
    @Column(nullable = false)
    var available: Boolean = false,
    /**
     * Provider data Sync 과정에서 자동으로 생성된 core 인 경우입니다. <br>
     * 관리자에 의해 체크가 필요한 경우를 나타냅니다. <br>
     */
    @Column(nullable = false)
    var autoGenerated: Boolean = true,
    @OneToOne(mappedBy = "core", fetch = FetchType.LAZY)
    var apiSports: FixtureApiSports? = null,
) {
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null) return false
        val oEffectiveClass =
            if (other is HibernateProxy) other.hibernateLazyInitializer.persistentClass else other.javaClass
        val thisEffectiveClass =
            if (this is HibernateProxy) this.hibernateLazyInitializer.persistentClass else this.javaClass
        if (thisEffectiveClass != oEffectiveClass) return false
        other as FixtureCore

        return id != null && id == other.id
    }

    override fun hashCode(): Int = if (this is HibernateProxy) this.hibernateLazyInitializer.persistentClass.hashCode() else javaClass.hashCode()

    @Override
    override fun toString(): String =
        this::class.simpleName +
            "(  id = $id   ,   uid = $uid   ,   kickoff = $kickoff   ,   status = $statusText   ,   statusShort = $statusCode   ,   elapsedMin = $elapsedMin   ,   goalsHome = $goalsHome   ,   goalsAway = $goalsAway   ,   finished = $finished   ,   available = $available   ,   autoGenerated = $autoGenerated )"
}
