package com.footballay.core.infra.persistence.core.entity

import jakarta.persistence.Column
import jakarta.persistence.Entity
import jakarta.persistence.FetchType
import jakarta.persistence.GeneratedValue
import jakarta.persistence.GenerationType
import jakarta.persistence.Id
import jakarta.persistence.Index
import jakarta.persistence.JoinColumn
import jakarta.persistence.ManyToOne
import jakarta.persistence.Table
import jakarta.persistence.UniqueConstraint
import java.time.LocalDate

/**
 * 리그의 시즌 인스턴스를 나타내는 Core 엔티티입니다.
 *
 * 같은 [LeagueCore] 라도 시즌별 fixture 수집/스케줄링 경계가 다르므로,
 * season-aware 작업은 이 엔티티를 기준으로 범위를 제한합니다.
 */
@Entity
@Table(
    name = "league_season_core",
    uniqueConstraints = [
        UniqueConstraint(
            name = "uc_league_season_core_league_year",
            columnNames = ["league_core_id", "season_year"],
        ),
    ],
    indexes = [
        Index(name = "idx_league_season_core_league_current", columnList = "league_core_id,current"),
    ],
)
data class LeagueSeasonCore(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "league_core_id", nullable = false)
    var league: LeagueCore,
    @Column(name = "season_year", nullable = false)
    var seasonYear: Int,
    @Column(name = "season_start")
    var seasonStart: LocalDate? = null,
    @Column(name = "season_end")
    var seasonEnd: LocalDate? = null,
    @Column(name = "current", nullable = false)
    var current: Boolean = false,
    @Column(name = "auto_generated", nullable = false)
    var autoGenerated: Boolean = true,
)
