package com.footballay.core.infra.persistence.core.entity

import com.footballay.core.infra.persistence.apisports.entity.PlayerApiSports
import jakarta.persistence.*

@Entity
@Table(name = "refac_players")
data class PlayerCore(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,
    /**
     * 외부 노출 ID
     */
    @Column(name = "uid", unique = true, nullable = false)
    var uid: String,
    /**
     * 선수 이름. API 에서 제공하는 네임 기반으로 채워지며 경우에 따라 풀네임 또는 흔히 알려진 이름만 저장될 수도 있습니다.
     */
    @Column(nullable = false)
    var name: String,
    var firstname: String? = null,
    var lastname: String? = null,
    var age: Int? = null,
    var nationality: String? = null,
    var position: String? = null,
    /**
     * Provider data Sync 과정에서 자동으로 생성된 core 인 경우입니다. <br>
     * 관리자에 의해 체크가 필요한 경우를 나타냅니다. <br>
     */
    @Column(nullable = false)
    var autoGenerated: Boolean = true,
    @OneToOne(mappedBy = "playerCore")
    var apiSportsPlayer: PlayerApiSports? = null,
)
