package com.footballay.core.infra.persistence.core.entity

import jakarta.persistence.*
import java.time.LocalDate

@Entity
@Table(name = "refac_players")
data class PlayerCore(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,

    /**
     * 외부 노출 ID
     */
    @Column(name = "uid", unique = true)
    var uid: String,

    var name: String,

    var firstname: String? = null,

    var lastname: String? = null,

    var age: Int? = null,

    var nationality: String? = null,

    var position: String? = null,

    /**
     * Provider data Sync 과정에서 자동으로 생성된 core 인 경우입니다. <br>
     * 관리자에 의해 체크가 필요한 경우를 나타냅니다. <br>
     */
    var autoGenerated: Boolean = true
)
