package com.footballay.core.infra.persistence.core.entity

import jakarta.persistence.*

@Entity
@Table(name = "refac_teams")
data class TeamCore(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    var id: Long? = null,

    /**
     * 외부 노출 ID
     */
    @Column(name = "uid", unique = true)
    var uid: String,

    var name: String,

    var code: String? = null,

    var country: String? = null,

    var founded: Int? = null,

    var national: Boolean = false,

    var available: Boolean = false,

    /**
     * Core 엔티티에도 apiId를 두면, 동일 팀 중복여부 검사 시 편함
     */
    var apiId: Long? = null,

    /**
     * Provider data Sync 과정에서 자동으로 생성된 core 인 경우입니다. <br>
     * 관리자에 의해 체크가 필요한 경우를 나타냅니다. <br>
     */
    var autoGenerated: Boolean = true
)
