package com.footballay.core.backbone.core.player

/**
 * PlayerCore 엔티티 생성에 필요한 데이터
 */
data class PlayerCoreCreateDto(
    val name: String,
    val autoGenerated: Boolean = true,
    val available: Boolean = false,
)
