package com.footballay.core.infra.facade

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.ArgumentMatchers.any
import org.mockito.BDDMockito.given
import org.mockito.InjectMocks
import org.mockito.Mock
import org.mockito.Mockito.never
import org.mockito.Mockito.verify
import org.mockito.junit.jupiter.MockitoExtension
import java.util.Optional

/**
 * AvailableLeagueFacade 단위 테스트
 *
 * Repository를 Mock으로 주입하여 Facade 로직만 테스트합니다.
 */
@ExtendWith(MockitoExtension::class)
class AvailableLeagueFacadeTest {
    @Mock
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @InjectMocks
    private lateinit var facade: AvailableLeagueFacade

    @Test
    fun `League available 설정 성공`() {
        // Given
        val leagueId = 39L
        val leagueUid = "league_uid_123"

        val leagueCore = createLeagueCore(
            id = leagueId,
            uid = leagueUid,
            available = false,
        )

        // findByIdOrNull은 findById의 확장 함수이므로 findById를 mock
        given(leagueCoreRepository.findById(leagueId)).willReturn(Optional.of(leagueCore))
        // save()는 저장된 엔티티를 반환하므로 동일 객체 반환
        given(leagueCoreRepository.save(any(LeagueCore::class.java))).willReturn(leagueCore)

        // When
        val result = facade.setLeagueAvailable(leagueId, true)

        // Then
        assertThat(result).isInstanceOf(DomainResult.Success::class.java)
        assertThat((result as DomainResult.Success).value).isEqualTo(leagueUid)
        assertThat(leagueCore.available).isTrue()

        verify(leagueCoreRepository).save(leagueCore)
    }

    @Test
    fun `League unavailable 설정 성공`() {
        // Given
        val leagueId = 39L
        val leagueUid = "league_uid_123"

        val leagueCore = createLeagueCore(
            id = leagueId,
            uid = leagueUid,
            available = true,
        )

        // findByIdOrNull은 findById의 확장 함수이므로 findById를 mock
        given(leagueCoreRepository.findById(leagueId)).willReturn(Optional.of(leagueCore))
        // save()는 저장된 엔티티를 반환하므로 동일 객체 반환
        given(leagueCoreRepository.save(any(LeagueCore::class.java))).willReturn(leagueCore)

        // When
        val result = facade.setLeagueAvailable(leagueId, false)

        // Then
        assertThat(result).isInstanceOf(DomainResult.Success::class.java)
        assertThat((result as DomainResult.Success).value).isEqualTo(leagueUid)
        assertThat(leagueCore.available).isFalse()

        verify(leagueCoreRepository).save(leagueCore)
    }

    @Test
    fun `존재하지 않는 League는 NotFound 반환`() {
        // Given
        val leagueId = 99999L

        // findByIdOrNull은 findById의 확장 함수이므로 findById를 mock (Optional.empty())
        given(leagueCoreRepository.findById(leagueId)).willReturn(Optional.empty())

        // When
        val result = facade.setLeagueAvailable(leagueId, true)

        // Then
        assertThat(result).isInstanceOf(DomainResult.Fail::class.java)
        val fail = result as DomainResult.Fail
        assertThat(fail.error).isInstanceOf(DomainFail.NotFound::class.java)
        val notFound = fail.error as DomainFail.NotFound
        assertThat(notFound.resource).isEqualTo("LEAGUE_CORE")
        assertThat(notFound.id).isEqualTo("99999")

        verify(leagueCoreRepository, never()).save(any())
    }

    /**
     * 테스트용 LeagueCore 생성 헬퍼
     */
    private fun createLeagueCore(
        id: Long,
        uid: String,
        available: Boolean,
    ): LeagueCore {
        return LeagueCore(
            id = id,
            uid = uid,
            name = "Test League",
            available = available,
            autoGenerated = false,
        )
    }
}

