package com.footballay.core.infra.facade

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.scheduler.MatchCollectLiveJobReconciler
import com.footballay.core.infra.scheduler.ReconcileError
import com.footballay.core.infra.scheduler.ReconcileResult
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.BDDMockito.given
import org.mockito.Mock
import org.mockito.Mockito.times
import org.mockito.Mockito.verify
import org.mockito.junit.jupiter.MockitoExtension

@ExtendWith(MockitoExtension::class)
class LeagueMatchCollectFacadeTest {
    @Mock
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Mock
    private lateinit var matchCollectLiveJobReconciler: MatchCollectLiveJobReconciler

    private lateinit var facade: LeagueMatchCollectFacade

    @BeforeEach
    fun setUp() {
        facade =
            LeagueMatchCollectFacade(
                leagueCoreRepository = leagueCoreRepository,
                matchCollectLiveJobReconciler = matchCollectLiveJobReconciler,
            )
    }

    @Test
    fun `league matchCollect 값을 변경하고 reconcile을 실행한다`() {
        val league = createLeague(matchCollect = MatchCollect.NONE)
        given(leagueCoreRepository.findByUid(league.uid)).willReturn(league)
        given(matchCollectLiveJobReconciler.reconcileLeague(league.uid))
            .willReturn(ReconcileResult.empty(fixtureUid = null, leagueUid = league.uid))

        val result = facade.setLeagueMatchCollectByCoreUid(league.uid, MatchCollect.FINISHED)

        assertThat(result).isInstanceOf(DomainResult.Success::class.java)
        val success = result as DomainResult.Success
        assertThat(success.value.leagueCoreUid).isEqualTo(league.uid)
        assertThat(success.value.matchCollect).isEqualTo(MatchCollect.FINISHED)
        assertThat(success.value.reconcileResult.success).isTrue()
        assertThat(league.matchCollect).isEqualTo(MatchCollect.FINISHED)
        verify(matchCollectLiveJobReconciler).reconcileLeague(league.uid)
    }

    @Test
    fun `league가 없으면 NotFound를 반환하고 reconcile하지 않는다`() {
        val leagueUid = "missing-league"
        given(leagueCoreRepository.findByUid(leagueUid)).willReturn(null)

        val result = facade.setLeagueMatchCollectByCoreUid(leagueUid, MatchCollect.LIVE)

        assertThat(result).isInstanceOf(DomainResult.Fail::class.java)
        val fail = result as DomainResult.Fail
        assertThat(fail.error).isInstanceOf(DomainFail.NotFound::class.java)
        val notFound = fail.error as DomainFail.NotFound
        assertThat(notFound.resource).isEqualTo("LEAGUE_CORE")
        assertThat(notFound.id).isEqualTo(leagueUid)
    }

    @Test
    fun `reconcile 실패 시 이전 matchCollect 값으로 되돌린다`() {
        val league = createLeague(matchCollect = MatchCollect.NONE)
        val failed =
            ReconcileResult.empty(fixtureUid = null, leagueUid = league.uid).copy(
                success = false,
                errors =
                    listOf(
                        ReconcileError(
                            fixtureUid = null,
                            leagueUid = league.uid,
                            phase = null,
                            operation = "test",
                            message = "failed",
                        ),
                    ),
            )
        val restored = ReconcileResult.empty(fixtureUid = null, leagueUid = league.uid)

        given(leagueCoreRepository.findByUid(league.uid)).willReturn(league)
        given(matchCollectLiveJobReconciler.reconcileLeague(league.uid))
            .willReturn(failed, restored)

        val result = facade.setLeagueMatchCollectByCoreUid(league.uid, MatchCollect.LIVE)

        assertThat(result).isInstanceOf(DomainResult.Fail::class.java)
        assertThat((result as DomainResult.Fail).error).isInstanceOf(DomainFail.Unknown::class.java)
        assertThat(league.matchCollect).isEqualTo(MatchCollect.NONE)
        verify(matchCollectLiveJobReconciler, times(2)).reconcileLeague(league.uid)
    }

    private fun createLeague(matchCollect: MatchCollect): LeagueCore =
        LeagueCore(
            id = 1L,
            uid = "league-1",
            name = "League 1",
            available = true,
            matchCollect = matchCollect,
            autoGenerated = false,
        )
}
