package com.footballay.core.web.admin.core.service

import com.footballay.core.domain.fixture.FixtureStatusCode
import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.domain.matchcollect.MatchCollectStatus
import com.footballay.core.infra.persistence.core.entity.FixtureCore
import com.footballay.core.infra.persistence.core.entity.FixtureMatchCollectState
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import com.footballay.core.infra.persistence.core.repository.FixtureMatchCollectStateRepository
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.Mock
import org.mockito.junit.jupiter.MockitoExtension
import org.mockito.kotlin.argumentCaptor
import org.mockito.kotlin.eq
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever
import org.springframework.data.domain.PageImpl
import org.springframework.data.domain.PageRequest
import org.springframework.data.domain.Pageable
import java.time.Instant

@ExtendWith(MockitoExtension::class)
class AdminMatchCollectQueryWebServiceTest {
    @Mock
    private lateinit var stateRepository: FixtureMatchCollectStateRepository

    @Test
    fun `match collect state page를 admin response로 변환한다`() {
        val service = AdminMatchCollectQueryWebService(stateRepository)
        val state =
            FixtureMatchCollectState(
                fixture = fixture(),
                matchCollectStatus = MatchCollectStatus.DATA_INCOMPLETE_NEEDS_ADMIN,
                lastCollectedAt = Instant.parse("2026-06-20T12:00:00Z"),
            )
        whenever(
            stateRepository.findAdminStates(
                leagueUid = eq("league-1"),
                fixtureUid = eq(null),
                status = eq(null),
                incompleteOnly = eq(true),
                pageable = org.mockito.kotlin.any(),
            ),
        ).thenReturn(PageImpl(listOf(state), PageRequest.of(0, 50), 1))

        val result =
            service.findStates(
                leagueUid = "league-1",
                fixtureUid = null,
                status = null,
                incompleteOnly = true,
                page = 0,
                size = 50,
            )

        assertThat(result.totalElements).isEqualTo(1)
        assertThat(result.content).hasSize(1)
        assertThat(result.content.first().fixtureUid).isEqualTo("fixture-1")
        assertThat(result.content.first().leagueUid).isEqualTo("league-1")
        assertThat(result.content.first().seasonYear).isEqualTo(2026)
        assertThat(result.content.first().leagueMatchCollect).isEqualTo(MatchCollect.LIVE)
        assertThat(result.content.first().matchCollectStatus).isEqualTo(MatchCollectStatus.DATA_INCOMPLETE_NEEDS_ADMIN)
    }

    @Test
    fun `page와 size를 안전한 범위로 보정한다`() {
        val service = AdminMatchCollectQueryWebService(stateRepository)
        val pageableCaptor = argumentCaptor<Pageable>()
        whenever(
            stateRepository.findAdminStates(
                leagueUid = eq(null),
                fixtureUid = eq(null),
                status = eq(MatchCollectStatus.FAIL_END),
                incompleteOnly = eq(false),
                pageable = org.mockito.kotlin.any(),
            ),
        ).thenReturn(PageImpl(emptyList(), PageRequest.of(0, 200), 0))

        service.findStates(
            leagueUid = "",
            fixtureUid = "",
            status = MatchCollectStatus.FAIL_END,
            incompleteOnly = false,
            page = -1,
            size = 999,
        )

        verify(stateRepository).findAdminStates(
            leagueUid = eq(null),
            fixtureUid = eq(null),
            status = eq(MatchCollectStatus.FAIL_END),
            incompleteOnly = eq(false),
            pageable = pageableCaptor.capture(),
        )
        assertThat(pageableCaptor.firstValue.pageNumber).isZero()
        assertThat(pageableCaptor.firstValue.pageSize).isEqualTo(200)
    }

    private fun fixture(): FixtureCore {
        val league =
            LeagueCore(
                id = 1L,
                uid = "league-1",
                name = "League",
                available = true,
                matchCollect = MatchCollect.LIVE,
                autoGenerated = false,
            )
        val season =
            LeagueSeasonCore(
                id = 1L,
                league = league,
                seasonYear = 2026,
                current = true,
                autoGenerated = false,
            )
        return FixtureCore(
            id = 1L,
            uid = "fixture-1",
            kickoff = Instant.parse("2026-06-20T09:00:00Z"),
            statusText = FixtureStatusCode.FT.code,
            statusCode = FixtureStatusCode.FT,
            league = league,
            leagueSeason = season,
            homeTeam = null,
            awayTeam = null,
            available = false,
            autoGenerated = false,
        )
    }
}
