footballay:
  apisports:
    scheme: https
    host: v3.football.api-sports.io
    url: v3.football.api-sports.io
    headers:
      x-rapidapi-host-name: "X-RapidAPI-Host"
      x-rapidapi-host-value: "v3.football.api-sports.io"
      x-rapidapi-key-name: x-rapidapi-key
      x-rapidapi-key-value: ${FOOTBALLAY_APISPORTS_X_RAPIDAPI_KEY_VALUE}
  data-quality:
    enabled: ${FOOTBALLAY_DATA_QUALITY_ENABLED:false}
    raw-collection:
      enabled: ${FOOTBALLAY_DATA_QUALITY_RAW_COLLECTION_ENABLED:false}
    storage:
      enabled: ${FOOTBALLAY_DATA_QUALITY_STORAGE_ENABLED:false}
      type: s3
      bucket: ${FOOTBALLAY_DATA_QUALITY_S3_BUCKET}
      region: ${FOOTBALLAY_DATA_QUALITY_S3_REGION}
      s3-download-url-ttl: 10m
    kafka:
      enabled: ${FOOTBALLAY_DATA_QUALITY_KAFKA_ENABLED:false}
      producer:
        enabled: ${FOOTBALLAY_DATA_QUALITY_KAFKA_PRODUCER_ENABLED:false}

aws:
  cloudfront:
    domain: "https://static.gyechunhoe.com"
    keyPairId: ${AWS_CLOUDFRONT_KEY_PAIR_ID}
    privateKeyPath: ${AWS_CLOUDFRONT_PRIVATE_KEY_PATH}
    publicKeyPath: ${AWS_CLOUDFRONT_PUBLIC_KEY_PATH}
  s3:
    public-domain: "https://static.gyechunhoe.com"
    accessKey: ${AWS_S3_ACCESS_KEY}
    secretKey: ${AWS_S3_SECRET_KEY}
    region: ${AWS_S3_REGION}
    bucket-name: ${AWS_S3_BUCKET_NAME}

spring:
  data:
    mongodb:
      uri: ${FOOTBALLAY_DATA_QUALITY_MONGODB_URI}
  kafka:
    bootstrap-servers: ${AIVEN_KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      ssl.truststore.location: ${AIVEN_KAFKA_CA_PATH}
      ssl.truststore.type: PEM
      sasl.jaas.config: >-
        org.apache.kafka.common.security.scram.ScramLoginModule required username="${AIVEN_KAFKA_CORE_USERNAME}" password="${AIVEN_KAFKA_CORE_PASSWORD}";
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379
      password: ${SPRING_DATA_REDIS_PASSWORD}

rapidapi:
  football:
    key: ${RAPIDAPI_FOOTBALL_KEY}

sportmonks:
  key: ${SPORTMONKS_KEY}

discord:
  role:
    developer: ${DISCORD_ROLE_DEVELOPER}
  webhook:
    lineup: ${DISCORD_WEBHOOK_LINEUP}
    match: ${DISCORD_WEBHOOK_MATCH}
    id-null: ${DISCORD_WEBHOOK_ID_NULL}

secret:
  key: ${SECRET_KEY}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

custom:
  login:
    remember-me-key: ${CUSTOM_LOGIN_REMEMBER_ME_KEY}

loki:
  url: ${LOKI_URL}
  username: ${LOKI_USERNAME}
  password: ${LOKI_PASSWORD}
