package com.footballay.core.infra.core.dto

/**
 * LeagueCore 엔티티 생성에 필요한 데이터
 */
data class LeagueCoreCreateDto(
    val name: String,
    val autoGenerated: Boolean = true,
    val available: Boolean = false
) 