package com.footballay.core.domain.matchcollect

import com.footballay.core.domain.league.MatchCollect
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.extension.ExtendWith
import org.mockito.Mock
import org.mockito.junit.jupiter.MockitoExtension
import org.mockito.kotlin.eq
import org.mockito.kotlin.verify
import org.mockito.kotlin.whenever
import org.springframework.data.domain.PageImpl
import org.springframework.data.domain.PageRequest

@ExtendWith(MockitoExtension::class)
class AdminMatchCollectQueryFacadeTest {
    @Mock
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Mock
    private lateinit var queryDomainService: AdminMatchCollectQueryDomainService

    private val mapper = AdminMatchCollectQueryModelMapper()

    @Test
    fun `status가 없고 incompleteOnly false면 모든 status로 전역 조회한다`() {
        val pageable = PageRequest.of(0, 50)
        whenever(
            queryDomainService.findAllMatchCollectStatesByStatuses(
                statuses = eq(MatchCollectStatus.entries),
                pageable = eq(pageable),
            ),
        ).thenReturn(PageImpl(emptyList(), pageable, 0))

        facade().findAllStatePage(status = null, incompleteOnly = false, pageable = pageable)

        verify(queryDomainService).findAllMatchCollectStatesByStatuses(
            statuses = eq(MatchCollectStatus.entries),
            pageable = eq(pageable),
        )
    }

    @Test
    fun `status가 없고 incompleteOnly true면 incomplete status로 전역 조회한다`() {
        val pageable = PageRequest.of(0, 50)
        whenever(
            queryDomainService.findAllMatchCollectStatesByStatuses(
                statuses = eq(MatchCollectStatus.INCOMPLETE_STATUSES),
                pageable = eq(pageable),
            ),
        ).thenReturn(PageImpl(emptyList(), pageable, 0))

        facade().findAllStatePage(status = null, incompleteOnly = true, pageable = pageable)

        verify(queryDomainService).findAllMatchCollectStatesByStatuses(
            statuses = eq(listOf(MatchCollectStatus.DATA_INCOMPLETE_NEEDS_ADMIN, MatchCollectStatus.FAIL_END)),
            pageable = eq(pageable),
        )
    }

    @Test
    fun `incomplete status와 incompleteOnly true면 해당 status만 조회한다`() {
        val pageable = PageRequest.of(0, 50)
        whenever(leagueCoreRepository.findByUid("league-1")).thenReturn(league())
        whenever(
            queryDomainService.findMatchCollectStatesByLeagueUidAndStatuses(
                leagueUid = eq("league-1"),
                statuses = eq(listOf(MatchCollectStatus.FAIL_END)),
                pageable = eq(pageable),
            ),
        ).thenReturn(PageImpl(emptyList(), pageable, 0))

        facade().findLeagueStatePage(
            leagueUid = "league-1",
            status = MatchCollectStatus.FAIL_END,
            incompleteOnly = true,
            pageable = pageable,
        )

        verify(queryDomainService).findMatchCollectStatesByLeagueUidAndStatuses(
            leagueUid = eq("league-1"),
            statuses = eq(listOf(MatchCollectStatus.FAIL_END)),
            pageable = eq(pageable),
        )
    }

    @Test
    fun `complete status와 incompleteOnly true면 빈 status list로 조회해 빈 결과를 유도한다`() {
        val pageable = PageRequest.of(0, 50)
        whenever(
            queryDomainService.findMatchCollectStateByFixtureUidAndStatuses(
                fixtureUid = eq("fixture-1"),
                statuses = eq(emptyList()),
                pageable = eq(pageable),
            ),
        ).thenReturn(PageImpl(emptyList(), pageable, 0))

        val result =
            facade().findStatePageByFixtureUid(
                fixtureUid = "fixture-1",
                status = MatchCollectStatus.SUCCESS,
                incompleteOnly = true,
                pageable = pageable,
            )

        assertThat(result.content).isEmpty()
        verify(queryDomainService).findMatchCollectStateByFixtureUidAndStatuses(
            fixtureUid = eq("fixture-1"),
            statuses = eq(emptyList()),
            pageable = eq(pageable),
        )
    }

    private fun facade() =
        AdminMatchCollectQueryFacade(
            leagueCoreRepository = leagueCoreRepository,
            queryDomainService = queryDomainService,
            mapper = mapper,
        )

    private fun league() =
        LeagueCore(
            uid = "league-1",
            name = "League",
            available = true,
            matchCollect = MatchCollect.LIVE,
            autoGenerated = false,
        )
}
