package com.footballay.core.web.admin.league.service

import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.logger
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional

/**
 * AdminLeagueQueryWebService 통합 테스트
 *
 * ## 테스트 범위
 * - available=true인 리그 목록 조회
 * - DTO 매핑 검증
 *
 * @author Footballay Core Team
 */
@SpringBootTest
@ActiveProfiles("dev", "mockapi")
@Transactional
class AdminLeagueQueryWebServiceImplTest {
    val log = logger()

    @Autowired
    private lateinit var adminLeagueQueryWebService: AdminLeagueQueryWebService

    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @Test
    fun `available=true인 리그만 조회되어야 한다`() {
        // Given
        val availableLeague1 =
            LeagueCore(
                uid = "test_league_1",
                name = "Premier League",
                available = true,
                autoGenerated = false,
            )
        val availableLeague2 =
            LeagueCore(
                uid = "test_league_2",
                name = "La Liga",
                available = true,
                autoGenerated = false,
            )
        val unavailableLeague =
            LeagueCore(
                uid = "test_league_3",
                name = "Bundesliga",
                available = false,
                autoGenerated = false,
            )

        leagueCoreRepository.saveAll(listOf(availableLeague1, availableLeague2, unavailableLeague))
        em.flush()
        em.clear()

        // When
        val result = adminLeagueQueryWebService.findAvailableLeagues()

        // Then
        assertThat(result).hasSize(2)
        assertThat(result.map { it.name }).containsExactlyInAnyOrder("Premier League", "La Liga")
        assertThat(result.map { it.leagueId }).containsExactlyInAnyOrder(availableLeague1.id, availableLeague2.id)

        log.info("Available leagues: ${result.map { "${it.name}(${it.leagueId})" }}")
    }

    @Test
    fun `available=true인 리그가 없으면 빈 리스트 반환`() {
        // Given
        val unavailableLeague =
            LeagueCore(
                uid = "test_league_1",
                name = "Bundesliga",
                available = false,
                autoGenerated = false,
            )

        leagueCoreRepository.save(unavailableLeague)
        em.flush()
        em.clear()

        // When
        val result = adminLeagueQueryWebService.findAvailableLeagues()

        // Then
        assertThat(result).isEmpty()
        log.info("No available leagues found (expected)")
    }
}
