package com.footballay.core.web.admin.league.service

import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.logger
import jakarta.persistence.EntityManager
import jakarta.persistence.PersistenceContext
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.security.test.context.support.WithMockUser
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional

/**
 * AdminLeagueQueryWebService 통합 테스트
 *
 * ## 테스트 범위
 * - available=true인 리그 목록 조회
 * - DTO 매핑 검증
 *
 * @author Footballay Core Team
 */
@SpringBootTest
@ActiveProfiles("dev", "mockapi")
@Transactional
class AdminLeagueQueryWebServiceImplTest {
    val log = logger()

    @Autowired
    private lateinit var adminLeagueQueryWebService: AdminLeagueQueryWebService

    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @PersistenceContext
    private lateinit var em: EntityManager

    @WithMockUser(roles = ["ADMIN"])
    @Test
    fun `available=true인 리그만 조회되어야 한다`() {
        // Given
        val availableLeague1 = createLeagueCore("test_league_1", "Premier League", true)
        val availableLeague2 = createLeagueCore("test_league_2", "La Liga", true)
        val unavailableLeague = createLeagueCore("test_league_3", "Bundesliga", false)

        leagueCoreRepository.saveAll(listOf(availableLeague1, availableLeague2, unavailableLeague))
        em.flush()
        em.clear()

        // When
        val result = adminLeagueQueryWebService.findAvailableLeagues()

        // Then
        assertThat(result).hasSize(2)
        assertThat(result.map { it.name }).containsExactlyInAnyOrder("Premier League", "La Liga")
        assertThat(result.map { it.leagueId }).containsExactlyInAnyOrder(availableLeague1.id, availableLeague2.id)

        log.info("Available leagues: ${result.map { "${it.name}(${it.leagueId})" }}")
    }

    @WithMockUser(roles = ["ADMIN"])
    @Test
    fun `available=true인 리그가 없으면 빈 리스트 반환`() {
        // Given
        val unavailableLeague = createLeagueCore("test_league_1", "Serie A", false)

        leagueCoreRepository.save(unavailableLeague)
        em.flush()
        em.clear()

        // When
        val result = adminLeagueQueryWebService.findAvailableLeagues()

        // Then
        assertThat(result).isEmpty()
        log.info("No available leagues found (expected)")
    }

    private fun createLeagueCore(
        uid: String,
        name: String,
        available: Boolean,
    ): LeagueCore =
        LeagueCore(
            uid = uid,
            name = name,
            available = available,
            autoGenerated = false,
        )
}
