package com.footballay.core.infra.backbone.mock.resource

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.domain.model.LeagueModel
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.time.Instant

@Service
class MockLeagueService(
    private val leagueCoreRepository: LeagueCoreRepository,
    private val mockLeagueRepository: MockBackboneLeagueRepository,
    private val modelMapper: MockBackboneModelMapper,
    private val uidFactory: MockUidFactory,
    @Suppress("SpringJavaInjectionPointsAutowiringInspection")
    private val clock: Clock = Clock.systemUTC(),
) {
    @Transactional
    fun createLeague(command: MockLeagueCreateCommand): DomainResult<LeagueModel, DomainFail> {
        if (command.name.isBlank()) {
            return DomainResult.Fail(validationFail("LEAGUE_NAME_BLANK", "리그 이름은 비어 있을 수 없습니다.", "name"))
        }

        val league =
            leagueCoreRepository.save(
                LeagueCore(
                    uid = uidFactory.leagueCoreUid(),
                    name = command.name.trim(),
                    available = command.available,
                    autoGenerated = false,
                ),
            )
        val mockLeague =
            mockLeagueRepository.save(
                MockBackboneLeague(
                    mockUid = uidFactory.leagueMockUid(),
                    league = league,
                    scenarioUid = command.scenarioUid,
                    scenarioName = command.scenarioName,
                    createdAt = Instant.now(clock),
                ),
            )

        return DomainResult.Success(toModel(mockLeague))
    }

    @Transactional
    fun deleteLeague(leagueCoreUid: String): DomainResult<LeagueModel, DomainFail> {
        val mockLeague =
            mockLeagueRepository.findByLeagueCoreUid(leagueCoreUid)
                ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_LEAGUE", leagueCoreUid))
        val result = toModel(mockLeague)

        mockLeagueRepository.delete(mockLeague)
        leagueCoreRepository.delete(mockLeague.league)

        return DomainResult.Success(result)
    }

    fun toModel(mockLeague: MockBackboneLeague): LeagueModel =
        modelMapper.toLeagueModel(mockLeague.league)
}
