package com.footballay.core.infra.backbone.mock.resource

import com.footballay.core.common.result.DomainFail
import com.footballay.core.common.result.DomainResult
import com.footballay.core.domain.model.TeamModel
import com.footballay.core.infra.persistence.core.entity.TeamCore
import com.footballay.core.infra.persistence.core.repository.TeamCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneTeam
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneTeamRepository
import org.springframework.stereotype.Service
import org.springframework.transaction.annotation.Transactional
import java.time.Clock
import java.time.Instant

@Service
class MockTeamService(
    private val teamCoreRepository: TeamCoreRepository,
    private val mockTeamRepository: MockBackboneTeamRepository,
    private val modelMapper: MockBackboneModelMapper,
    private val uidFactory: MockUidFactory,
    @Suppress("SpringJavaInjectionPointsAutowiringInspection")
    private val clock: Clock = Clock.systemUTC(),
) {
    @Transactional
    fun createTeam(command: MockTeamCreateCommand): DomainResult<TeamModel, DomainFail> {
        if (command.name.isBlank()) {
            return DomainResult.Fail(validationFail("TEAM_NAME_BLANK", "팀 이름은 비어 있을 수 없습니다.", "name"))
        }

        val team =
            teamCoreRepository.save(
                TeamCore(
                    uid = uidFactory.teamCoreUid(),
                    name = command.name.trim(),
                    autoGenerated = false,
                ),
            )
        val mockTeam =
            mockTeamRepository.save(
                MockBackboneTeam(
                    mockUid = uidFactory.teamMockUid(),
                    team = team,
                    scenarioUid = command.scenarioUid,
                    scenarioName = command.scenarioName,
                    createdAt = Instant.now(clock),
                ),
            )

        return DomainResult.Success(toModel(mockTeam))
    }

    @Transactional
    fun deleteTeam(teamCoreUid: String): DomainResult<TeamModel, DomainFail> {
        val mockTeam =
            mockTeamRepository.findByTeamCoreUid(teamCoreUid)
                ?: return DomainResult.Fail(DomainFail.NotFound("MOCK_BACKBONE_TEAM", teamCoreUid))
        val result = toModel(mockTeam)

        mockTeamRepository.delete(mockTeam)
        teamCoreRepository.delete(mockTeam.team)

        return DomainResult.Success(result)
    }

    fun toModel(mockTeam: MockBackboneTeam): TeamModel =
        modelMapper.toTeamModel(mockTeam.team)
}
