package com.footballay.core.domain.facade

import com.footballay.core.common.result.DomainResult
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSports
import com.footballay.core.infra.persistence.apisports.repository.LeagueApiSportsRepository
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.repository.LeagueCoreRepository
import com.footballay.core.infra.persistence.mockbackbone.entity.MockBackboneLeague
import com.footballay.core.infra.persistence.mockbackbone.repository.MockBackboneLeagueRepository
import jakarta.persistence.EntityManager
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.transaction.annotation.Transactional
import java.time.Instant

@SpringBootTest
@ActiveProfiles("test")
@Transactional
class DesktopLeagueFacadeImplTest {
    @Autowired
    private lateinit var desktopLeagueFacade: DesktopLeagueFacade

    @Autowired
    private lateinit var leagueCoreRepository: LeagueCoreRepository

    @Autowired
    private lateinit var leagueApiSportsRepository: LeagueApiSportsRepository

    @Autowired
    private lateinit var mockBackboneLeagueRepository: MockBackboneLeagueRepository

    @Autowired
    private lateinit var entityManager: EntityManager

    private lateinit var apiSportsLeague: LeagueCore
    private lateinit var mockLeague: LeagueCore
    private lateinit var sharedLeague: LeagueCore

    @BeforeEach
    fun setUp() {
        apiSportsLeague = saveLeague("api-league", "ApiSports League")
        mockLeague = saveLeague("mock-league", "Mock League")
        sharedLeague = saveLeague("shared-league", "Shared League")
        saveLeague("core-only-league", "Core Only League")

        saveApiSportsLeague(apiSportsLeague, 39L)
        saveMockLeague(mockLeague)
        saveApiSportsLeague(sharedLeague, 140L)
        saveMockLeague(sharedLeague)

        entityManager.flush()
        entityManager.clear()
    }

    @Test
    fun `기본 available league 조회는 mock league를 제외한다`() {
        val result = desktopLeagueFacade.getAvailableLeagues()

        assertThat(result).isInstanceOf(DomainResult.Success::class.java)
        val leagues = (result as DomainResult.Success).value
        assertThat(leagues.map { it.uid }).containsExactly("api-league", "shared-league")
    }

    @Test
    fun `mock data option이 있으면 available league 조회에 mock league를 포함한다`() {
        val result =
            desktopLeagueFacade.getAvailableLeagues(
                MockDataReadOption(includeMockData = true),
            )

        assertThat(result).isInstanceOf(DomainResult.Success::class.java)
        val leagues = (result as DomainResult.Success).value
        assertThat(leagues.map { it.uid }).containsExactly("api-league", "mock-league", "shared-league")
    }

    private fun saveLeague(
        uid: String,
        name: String,
    ): LeagueCore =
        leagueCoreRepository.save(
            LeagueCore(
                uid = uid,
                name = name,
                available = true,
                autoGenerated = false,
            ),
        )

    private fun saveApiSportsLeague(
        league: LeagueCore,
        apiId: Long,
    ) {
        leagueApiSportsRepository.save(
            LeagueApiSports(
                apiId = apiId,
                name = league.name,
                leagueCore = league,
                available = true,
            ),
        )
    }

    private fun saveMockLeague(league: LeagueCore) {
        mockBackboneLeagueRepository.save(
            MockBackboneLeague(
                mockUid = "mock-league-${league.uid}",
                league = league,
                createdAt = Instant.parse("2026-06-01T00:00:00Z"),
            ),
        )
    }
}
