services:
  redis:
    image: redis:7.2.4-alpine
    container_name: footballay-dev-redis
    command: redis-server --requirepass 1234 --port 6379
    ports:
      - "6379:6379"

  postgres:
    image: postgres:17.4
    container_name: footballay-dev-postgres
    environment:
      POSTGRES_DB: footballay_core
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev1234
      TZ: Asia/Seoul
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
