services:
  redis:
    image: redis:7.2.4-alpine
    container_name: footballay-dev-redis
    command: redis-server --requirepass 1234 --port 6379
    ports:
      - "6379:6379"

  mariadb:
    image: mariadb:latest
    container_name: footballay-dev-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: footballay
      MARIADB_USER: dev
      MARIADB_PASSWORD: dev1234
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
    driver: local