package com.footballay.core.infra.apisports.backbone.sync.league

import com.footballay.core.infra.apisports.shared.dto.LeagueApiSportsCoverageCreateDto
import com.footballay.core.infra.apisports.shared.dto.LeagueApiSportsCreateDto
import com.footballay.core.infra.apisports.shared.dto.LeagueApiSportsSeasonCreateDto
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSports
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSportsCoverage
import com.footballay.core.infra.persistence.apisports.entity.LeagueApiSportsSeason
import com.footballay.core.infra.persistence.core.entity.LeagueCore
import com.footballay.core.infra.persistence.core.entity.LeagueSeasonCore
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test
import java.time.LocalDate

class LeagueApiSportsSeasonSyncPlanFactoryTest {
    private val planFactory = LeagueApiSportsSeasonSyncPlanFactory()

    @Test
    @DisplayName("Core X / Provider X이면 core와 provider를 모두 만들고 연결하는 plan을 만든다")
    fun `core missing provider missing creates both seasons and link`() {
        val league = leagueFixture()

        val plan = createPlan(league = league)

        val resolvedPair = plan.resolvedPairs.single()

        assertThat(resolvedPair.case).isEqualTo(SeasonPairCase.CORE_MISSING_PROVIDER_MISSING)
        assertThat(resolvedPair.coreSeason.id).isNull()
        assertThat(resolvedPair.providerSeason.id).isNull()
        assertThat(resolvedPair.providerSeason.leagueSeasonCore).isSameAs(resolvedPair.coreSeason)
        assertThat(plan.coreSeasonsToSave.keys).containsExactly(CoreSeasonIdentity(league.core.id!!, 2024))
        assertThat(plan.providerSeasonsToSave.keys).containsExactly(ProviderSeasonIdentity(league.api.id!!, 2024))
    }

    @Test
    @DisplayName("Core O / Provider X이면 기존 core를 재사용하고 provider만 새로 만든다")
    fun `core exists provider missing reuses core and creates provider`() {
        val league = leagueFixture()
        val existingCoreSeason =
            coreSeason(
                id = 100L,
                league = league.core,
                seasonYear = 2024,
                current = false,
                autoGenerated = false,
            )

        val plan =
            createPlan(
                league = league,
                existingCoreSeasons = mapOf(CoreSeasonIdentity(league.core.id!!, 2024) to existingCoreSeason),
            )

        val resolvedPair = plan.resolvedPairs.single()

        assertThat(resolvedPair.case).isEqualTo(SeasonPairCase.CORE_EXISTS_PROVIDER_MISSING)
        assertThat(resolvedPair.coreSeason).isSameAs(existingCoreSeason)
        assertThat(resolvedPair.coreSeason.autoGenerated).isFalse()
        assertThat(resolvedPair.providerSeason.id).isNull()
        assertThat(resolvedPair.providerSeason.leagueSeasonCore).isSameAs(existingCoreSeason)
        assertThat(plan.coreSeasonsToSave.values).containsExactly(existingCoreSeason)
        assertThat(plan.providerSeasonsToSave.values).containsExactly(resolvedPair.providerSeason)
    }

    @Test
    @DisplayName("Core X / Provider O이면 core를 만들고 기존 provider link를 보정한다")
    fun `core missing provider exists creates core and reuses provider`() {
        val league = leagueFixture()
        val existingProviderSeason =
            providerSeason(
                id = 200L,
                leagueApiSports = league.api,
                seasonYear = 2024,
                leagueSeasonCore = null,
            )

        val plan =
            createPlan(
                league = league,
                existingProviderSeasons = mapOf(ProviderSeasonIdentity(league.api.id!!, 2024) to existingProviderSeason),
            )

        val resolvedPair = plan.resolvedPairs.single()

        assertThat(resolvedPair.case).isEqualTo(SeasonPairCase.CORE_MISSING_PROVIDER_EXISTS)
        assertThat(resolvedPair.coreSeason.id).isNull()
        assertThat(resolvedPair.providerSeason).isSameAs(existingProviderSeason)
        assertThat(existingProviderSeason.leagueSeasonCore).isSameAs(resolvedPair.coreSeason)
        assertThat(plan.coreSeasonsToSave.values).containsExactly(resolvedPair.coreSeason)
        assertThat(plan.providerSeasonsToSave.values).containsExactly(existingProviderSeason)
    }

    @Test
    @DisplayName("Core O / Provider O이고 link가 정상이면 값 변화가 없을 때 save 대상에 넣지 않는다")
    fun `core exists provider exists with correct link and same fields produces no save`() {
        val league = leagueFixture()
        val existingCoreSeason =
            coreSeason(
                id = 100L,
                league = league.core,
                seasonYear = 2024,
                seasonStart = LocalDate.parse("2024-08-01"),
                seasonEnd = LocalDate.parse("2025-05-31"),
                current = true,
            )
        val existingProviderSeason =
            providerSeason(
                id = 200L,
                leagueApiSports = league.api,
                seasonYear = 2024,
                seasonStart = LocalDate.parse("2024-08-01"),
                seasonEnd = LocalDate.parse("2025-05-31"),
                coverage = coverageEntity(standings = true),
                leagueSeasonCore = existingCoreSeason,
            )

        val plan =
            createPlan(
                league = league,
                existingCoreSeasons = mapOf(CoreSeasonIdentity(league.core.id!!, 2024) to existingCoreSeason),
                existingProviderSeasons = mapOf(ProviderSeasonIdentity(league.api.id!!, 2024) to existingProviderSeason),
            )

        val resolvedPair = plan.resolvedPairs.single()

        assertThat(resolvedPair.case).isEqualTo(SeasonPairCase.CORE_EXISTS_PROVIDER_EXISTS)
        assertThat(plan.coreSeasonsToSave).isEmpty()
        assertThat(plan.providerSeasonsToSave).isEmpty()
    }

    @Test
    @DisplayName("Core O / Provider O이고 link가 wrong year이면 올바른 core로 교체하는 plan을 만든다")
    fun `core exists provider exists with wrong year link fixes provider link`() {
        val league = leagueFixture()
        val wrongCoreSeason = coreSeason(id = 99L, league = league.core, seasonYear = 2023)
        val correctCoreSeason = coreSeason(id = 100L, league = league.core, seasonYear = 2024)
        val existingProviderSeason =
            providerSeason(
                id = 200L,
                leagueApiSports = league.api,
                seasonYear = 2024,
                leagueSeasonCore = wrongCoreSeason,
            )

        val plan =
            createPlan(
                league = league,
                existingCoreSeasons = mapOf(CoreSeasonIdentity(league.core.id!!, 2024) to correctCoreSeason),
                existingProviderSeasons = mapOf(ProviderSeasonIdentity(league.api.id!!, 2024) to existingProviderSeason),
            )

        assertThat(plan.resolvedPairs.single().case).isEqualTo(SeasonPairCase.CORE_EXISTS_PROVIDER_EXISTS)
        assertThat(existingProviderSeason.leagueSeasonCore).isSameAs(correctCoreSeason)
        assertThat(plan.providerSeasonsToSave.values).containsExactly(existingProviderSeason)
    }

    @Test
    @DisplayName("currentSeason이 null이면 기존 current core season을 false로 바꾸는 plan을 만든다")
    fun `null current season clears existing current core seasons`() {
        val league = leagueFixture()
        val season2023 = coreSeason(id = 99L, league = league.core, seasonYear = 2023, current = true)

        val plan =
            createPlan(
                league = league,
                currentSeason = null,
                existingCoreSeasons = mapOf(CoreSeasonIdentity(league.core.id!!, 2023) to season2023),
            )

        assertThat(season2023.current).isFalse()
        assertThat(plan.coreSeasonsToSave.values).contains(season2023)
        assertThat(plan.resolvedPairs.single().coreSeason.current).isFalse()
    }

    private fun createPlan(
        league: LeagueFixture,
        currentSeason: Int? = 2024,
        existingCoreSeasons: Map<CoreSeasonIdentity, LeagueSeasonCore> = emptyMap(),
        existingProviderSeasons: Map<ProviderSeasonIdentity, LeagueApiSportsSeason> = emptyMap(),
    ): LeagueApiSportsSeasonSyncPlan =
        planFactory.createPlan(
            LeagueApiSportsSeasonPlanCommand(
                inputs =
                    listOf(
                        LeagueSeasonSyncInput(
                            leagueCreateDto =
                                leagueDto(
                                    apiId = league.api.apiId,
                                    currentSeason = currentSeason,
                                    seasons = listOf(seasonDto(2024)),
                                ),
                            leagueApiSportsId = league.api.id!!,
                            leagueCoreId = league.core.id!!,
                        ),
                    ),
                leagueApiSportsById = mapOf(league.api.id!! to league.api),
                leagueCoreById = mapOf(league.core.id!! to league.core),
                existingCoreSeasonsByIdentity = existingCoreSeasons,
                existingProviderSeasonsByIdentity = existingProviderSeasons,
            ),
        )

    private fun leagueFixture(): LeagueFixture {
        val leagueCore = LeagueCore(id = 1L, uid = "league-core", name = "Premier League")
        val leagueApiSports =
            LeagueApiSports(
                id = 10L,
                leagueCore = leagueCore,
                apiId = 39L,
                name = "Premier League",
                type = "League",
                countryName = "England",
            )
        return LeagueFixture(core = leagueCore, api = leagueApiSports)
    }

    private fun leagueDto(
        apiId: Long,
        currentSeason: Int?,
        seasons: List<LeagueApiSportsSeasonCreateDto>,
    ): LeagueApiSportsCreateDto =
        LeagueApiSportsCreateDto(
            apiId = apiId,
            name = "League $apiId",
            type = "League",
            logo = "https://example.com/logo_$apiId.png",
            countryName = "England",
            countryCode = "GB",
            countryFlag = "https://example.com/flag.png",
            currentSeason = currentSeason,
            seasons = seasons,
        )

    private fun seasonDto(year: Int): LeagueApiSportsSeasonCreateDto =
        LeagueApiSportsSeasonCreateDto(
            seasonYear = year,
            seasonStart = "$year-08-01",
            seasonEnd = "${year + 1}-05-31",
            coverage = coverage(),
        )

    private fun coverage(): LeagueApiSportsCoverageCreateDto =
        LeagueApiSportsCoverageCreateDto(
            fixturesEvents = true,
            fixturesLineups = true,
            fixturesStatistics = true,
            fixturesPlayers = true,
            standings = true,
            players = true,
            topScorers = true,
            topAssists = true,
            topCards = true,
            injuries = true,
            predictions = true,
            odds = true,
        )

    private fun coverageEntity(standings: Boolean): LeagueApiSportsCoverage =
        LeagueApiSportsCoverage(
            fixturesEvents = true,
            fixturesLineups = true,
            fixturesStatistics = true,
            fixturesPlayers = true,
            standings = standings,
            players = true,
            topScorers = true,
            topAssists = true,
            topCards = true,
            injuries = true,
            predictions = true,
            odds = true,
        )

    private fun coreSeason(
        id: Long,
        league: LeagueCore,
        seasonYear: Int,
        seasonStart: LocalDate? = null,
        seasonEnd: LocalDate? = null,
        current: Boolean = false,
        autoGenerated: Boolean = true,
    ): LeagueSeasonCore =
        LeagueSeasonCore(
            id = id,
            league = league,
            seasonYear = seasonYear,
            seasonStart = seasonStart,
            seasonEnd = seasonEnd,
            current = current,
            autoGenerated = autoGenerated,
        )

    private fun providerSeason(
        id: Long,
        leagueApiSports: LeagueApiSports,
        seasonYear: Int,
        seasonStart: LocalDate? = null,
        seasonEnd: LocalDate? = null,
        coverage: LeagueApiSportsCoverage? = null,
        leagueSeasonCore: LeagueSeasonCore? = null,
    ): LeagueApiSportsSeason =
        LeagueApiSportsSeason(
            id = id,
            leagueApiSports = leagueApiSports,
            seasonYear = seasonYear,
            seasonStart = seasonStart,
            seasonEnd = seasonEnd,
            coverage = coverage,
            leagueSeasonCore = leagueSeasonCore,
        )

    private data class LeagueFixture(
        val core: LeagueCore,
        val api: LeagueApiSports,
    )
}
