package com.footballay.core.infra.persistence.core.dto

import java.time.OffsetDateTime

/**
 * @see FixtureCore
 */
data class FixtureCoreDto(
    val id: Long,
    val uid: String,
    val kickoff: OffsetDateTime,
    val timestamp: Long,
    val status: String,
    val statusShort: String,
    val elapsedMin: Int,
    val goalsHome: Int,
    val goalsAway: Int,
    val available: Boolean,

    val leagueCoreId: Long,
    val homeTeamCoreId: Long,
    val awayTeamCoreId: Long,

    val autoGenerated: Boolean
)
