CREATE TABLE player_core_localization
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    core_id    BIGINT                                  NOT NULL,
    locale     VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255),
    short_name VARCHAR(255),
    CONSTRAINT pk_player_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_player_core_localization_core FOREIGN KEY (core_id) REFERENCES player_core (id) ON DELETE CASCADE,
    CONSTRAINT uc_player_core_localization_core_locale UNIQUE (core_id, locale)
);

CREATE TABLE team_core_localization
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    core_id    BIGINT                                  NOT NULL,
    locale     VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255),
    short_name VARCHAR(255),
    CONSTRAINT pk_team_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_team_core_localization_core FOREIGN KEY (core_id) REFERENCES team_core (id) ON DELETE CASCADE,
    CONSTRAINT uc_team_core_localization_core_locale UNIQUE (core_id, locale)
);

CREATE TABLE league_core_localization
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    core_id    BIGINT                                  NOT NULL,
    locale     VARCHAR(255)                            NOT NULL,
    name       VARCHAR(255),
    short_name VARCHAR(255),
    CONSTRAINT pk_league_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_league_core_localization_core FOREIGN KEY (core_id) REFERENCES league_core (id) ON DELETE CASCADE,
    CONSTRAINT uc_league_core_localization_core_locale UNIQUE (core_id, locale)
);

ALTER TABLE player_core DROP COLUMN name_ko;
ALTER TABLE team_core DROP COLUMN name_ko;
ALTER TABLE league_core DROP COLUMN name_ko;
