CREATE TABLE player_core_localization
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_core_uid VARCHAR(255)                            NOT NULL,
    locale          VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255),
    short_name      VARCHAR(255),
    ai_generated    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_player_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_player_core_localization_core FOREIGN KEY (player_core_uid) REFERENCES player_core (uid) ON DELETE CASCADE,
    CONSTRAINT uc_player_core_localization_core_locale UNIQUE (player_core_uid, locale)
);

CREATE TABLE team_core_localization
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_core_uid VARCHAR(255)                            NOT NULL,
    locale        VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255),
    short_name    VARCHAR(255),
    ai_generated  BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_team_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_team_core_localization_core FOREIGN KEY (team_core_uid) REFERENCES team_core (uid) ON DELETE CASCADE,
    CONSTRAINT uc_team_core_localization_core_locale UNIQUE (team_core_uid, locale)
);

CREATE TABLE league_core_localization
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_uid VARCHAR(255)                            NOT NULL,
    locale          VARCHAR(255)                            NOT NULL,
    name            VARCHAR(255),
    short_name      VARCHAR(255),
    ai_generated    BOOLEAN                                 NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_league_core_localization PRIMARY KEY (id),
    CONSTRAINT fk_league_core_localization_core FOREIGN KEY (league_core_uid) REFERENCES league_core (uid) ON DELETE CASCADE,
    CONSTRAINT uc_league_core_localization_core_locale UNIQUE (league_core_uid, locale)
);

ALTER TABLE player_core DROP COLUMN name_ko;
ALTER TABLE team_core DROP COLUMN name_ko;
ALTER TABLE league_core DROP COLUMN name_ko;
