CREATE TABLE anonymous_users
(
    id                   UUID                        NOT NULL,
    created_date         TIMESTAMP WITHOUT TIME ZONE,
    modified_date        TIMESTAMP WITHOUT TIME ZONE,
    last_connected_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    auto_remote_group_id BIGINT                      NOT NULL,
    CONSTRAINT pk_anonymous_users PRIMARY KEY (id)
);

CREATE TABLE apisports_match_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_api_id BIGINT,
    match_team_id  BIGINT,
    player_id      BIGINT,
    assist_id      BIGINT,
    sequence       INTEGER                                 NOT NULL,
    elapsed_time   INTEGER,
    extra_time     INTEGER,
    event_type     VARCHAR(255),
    detail         VARCHAR(255),
    comments       VARCHAR(255),
    CONSTRAINT pk_apisports_match_event PRIMARY KEY (id)
);

CREATE TABLE apisports_match_player
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_uid    VARCHAR(255)                            NOT NULL,
    player_apisports_id BIGINT,
    name                VARCHAR(255)                            NOT NULL,
    number              INTEGER,
    position            VARCHAR(255)                            NOT NULL,
    grid                VARCHAR(255),
    substitute          BOOLEAN                                 NOT NULL,
    match_team_id       BIGINT,
    CONSTRAINT pk_apisports_match_player PRIMARY KEY (id)
);

CREATE TABLE apisports_match_player_stat
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_id   BIGINT,
    minutes_played    INTEGER,
    shirt_number      INTEGER,
    position          VARCHAR(255),
    rating            DOUBLE PRECISION,
    is_captain        BOOLEAN,
    is_substitute     BOOLEAN,
    offsides          INTEGER,
    shots_total       INTEGER,
    shots_on_target   INTEGER,
    goals_total       INTEGER,
    goals_conceded    INTEGER,
    assists           INTEGER,
    saves             INTEGER,
    passes_total      INTEGER,
    key_passes        INTEGER,
    passes_accuracy   INTEGER,
    tackles_total     INTEGER,
    blocks            INTEGER,
    interceptions     INTEGER,
    duels_total       INTEGER,
    duels_won         INTEGER,
    dribbles_attempts INTEGER,
    dribbles_success  INTEGER,
    dribbles_past     INTEGER,
    fouls_drawn       INTEGER,
    fouls_committed   INTEGER,
    yellow_cards      INTEGER,
    red_cards         INTEGER,
    penalty_won       INTEGER,
    penalty_committed INTEGER,
    penalty_scored    INTEGER,
    penalty_missed    INTEGER,
    penalty_saved     INTEGER,
    CONSTRAINT pk_apisports_match_player_stat PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_apisports_id        BIGINT,
    formation                VARCHAR(255),
    winner                   BOOLEAN,
    team_statistics_id       BIGINT,
    player_color_primary     VARCHAR(255),
    player_color_number      VARCHAR(255),
    player_color_border      VARCHAR(255),
    goalkeeper_color_primary VARCHAR(255),
    goalkeeper_color_number  VARCHAR(255),
    goalkeeper_color_border  VARCHAR(255),
    CONSTRAINT pk_apisports_match_team PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team_stat
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shots_on_goal     INTEGER,
    shots_off_goal    INTEGER,
    total_shots       INTEGER,
    blocked_shots     INTEGER,
    shots_inside_box  INTEGER,
    shots_outside_box INTEGER,
    fouls             INTEGER,
    corner_kicks      INTEGER,
    offsides          INTEGER,
    ball_possession   VARCHAR(255),
    yellow_cards      INTEGER,
    red_cards         INTEGER,
    goalkeeper_saves  INTEGER,
    total_passes      INTEGER,
    passes_accurate   INTEGER,
    passes_percentage VARCHAR(255),
    goals_prevented   INTEGER,
    CONSTRAINT pk_apisports_match_team_stat PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team_xg
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_team_statistics_id BIGINT                                  NOT NULL,
    elapsed_time             INTEGER                                 NOT NULL,
    expected_goals           DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_apisports_match_team_xg PRIMARY KEY (id)
);

CREATE TABLE authorities
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT                                  NOT NULL,
    authority     VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (id)
);

CREATE TABLE auto_remote_group
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    modified_date  TIMESTAMP WITHOUT TIME ZONE,
    expired_at     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_active_at TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_autoremotegroup PRIMARY KEY (id)
);

CREATE TABLE custom_player_photos
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date      TIMESTAMP WITHOUT TIME ZONE,
    modified_date     TIMESTAMP WITHOUT TIME ZONE,
    preference_key_id BIGINT                                  NOT NULL,
    player_id         BIGINT                                  NOT NULL,
    user_file_path_id BIGINT,
    file_name         VARCHAR(255)                            NOT NULL,
    is_active         BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_custom_player_photos PRIMARY KEY (id)
);

CREATE TABLE expected_goals
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_statistics_id BIGINT                                  NOT NULL,
    elapsed            INTEGER,
    xg                 VARCHAR(255),
    CONSTRAINT pk_expectedgoals PRIMARY KEY (id)
);

CREATE TABLE fixture_api_sports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_core_id BIGINT,
    api_id          BIGINT                                  NOT NULL,
    referee         VARCHAR(255),
    date            TIMESTAMP WITH TIME ZONE,
    round           VARCHAR(255),
    prevent_update  BOOLEAN                                 NOT NULL,
    available       BOOLEAN                                 NOT NULL,
    venue_id        BIGINT,
    season_id       BIGINT,
    home_team_id    BIGINT,
    away_team_id    BIGINT,
    long_status     VARCHAR(255),
    short_status    VARCHAR(255),
    elapsed         INTEGER,
    extra           INTEGER,
    total_home      INTEGER,
    total_away      INTEGER,
    halftime_home   INTEGER,
    halftime_away   INTEGER,
    fulltime_home   INTEGER,
    fulltime_away   INTEGER,
    extratime_home  INTEGER,
    extratime_away  INTEGER,
    penalty_home    INTEGER,
    penalty_away    INTEGER,
    CONSTRAINT pk_fixtureapisports PRIMARY KEY (id)
);

CREATE TABLE fixture_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    kickoff        TIMESTAMP WITH TIME ZONE,
    status_text    VARCHAR(255),
    status_code    VARCHAR(255),
    elapsed_min    INTEGER,
    league_id      BIGINT,
    home_team_id   BIGINT,
    away_team_id   BIGINT,
    goals_home     INTEGER,
    goals_away     INTEGER,
    finished       BOOLEAN                                 NOT NULL,
    available      BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_fixture_core PRIMARY KEY (id)
);

CREATE TABLE fixture_event
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_id             BIGINT                                  NOT NULL,
    sequence               INTEGER                                 NOT NULL,
    time_elapsed           INTEGER,
    extra_time             INTEGER,
    type                   VARCHAR(255),
    detail                 VARCHAR(255)                            NOT NULL,
    comments               VARCHAR(255),
    team_id                BIGINT,
    match_player_id        BIGINT,
    match_player_assist_id BIGINT,
    CONSTRAINT pk_fixtureevent PRIMARY KEY (id)
);

CREATE TABLE fixtures
(
    fixture_id     BIGINT  NOT NULL,
    referee        VARCHAR(255),
    date           TIMESTAMP WITHOUT TIME ZONE,
    timezone       VARCHAR(255),
    timestamp      BIGINT,
    available      BOOLEAN NOT NULL,
    is_summer_time BOOLEAN NOT NULL,
    round          VARCHAR(255),
    live_status_id BIGINT,
    league_id      BIGINT  NOT NULL,
    home_team_id   BIGINT  NOT NULL,
    away_team_id   BIGINT  NOT NULL,
    CONSTRAINT pk_fixtures PRIMARY KEY (fixture_id)
);

CREATE TABLE last_cache_log
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_cache_type  VARCHAR(255)                            NOT NULL,
    parameters_json VARCHAR(255)                            NOT NULL,
    last_cached_at  TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_lastcachelog PRIMARY KEY (id)
);

CREATE TABLE league_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_id BIGINT,
    api_id         BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    type           VARCHAR(255),
    logo           VARCHAR(255),
    country_name   VARCHAR(255),
    country_code   VARCHAR(255),
    country_flag   VARCHAR(255),
    current_season INTEGER,
    available      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_league_apisports PRIMARY KEY (id)
);

CREATE TABLE league_apisports_season
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_year         INTEGER,
    season_start        date,
    season_end          date,
    league_apisports_id BIGINT,
    fixtures_events     BOOLEAN,
    fixtures_lineups    BOOLEAN,
    fixtures_statistics BOOLEAN,
    fixtures_players    BOOLEAN,
    standings           BOOLEAN,
    players             BOOLEAN,
    top_scorers         BOOLEAN,
    top_assists         BOOLEAN,
    top_cards           BOOLEAN,
    injuries            BOOLEAN,
    predictions         BOOLEAN,
    odds                BOOLEAN,
    CONSTRAINT pk_league_apisports_season PRIMARY KEY (id)
);

CREATE TABLE league_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    available      BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_league_core PRIMARY KEY (id)
);

CREATE TABLE league_team
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_id BIGINT,
    team_id   BIGINT,
    CONSTRAINT pk_leagueteam PRIMARY KEY (id)
);

CREATE TABLE league_team_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_id BIGINT                                  NOT NULL,
    team_core_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_league_team_core PRIMARY KEY (id)
);

CREATE TABLE leagues
(
    league_id      BIGINT       NOT NULL,
    created_date   TIMESTAMP WITHOUT TIME ZONE,
    modified_date  TIMESTAMP WITHOUT TIME ZONE,
    name           VARCHAR(255) NOT NULL,
    korean_name    VARCHAR(255),
    logo           VARCHAR(255),
    available      BOOLEAN      NOT NULL,
    current_season INTEGER,
    CONSTRAINT pk_leagues PRIMARY KEY (league_id)
);

CREATE TABLE live_status
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    long_status  VARCHAR(255),
    short_status VARCHAR(255),
    elapsed      INTEGER,
    home_score   INTEGER,
    away_score   INTEGER,
    CONSTRAINT pk_livestatus PRIMARY KEY (id)
);

CREATE TABLE match_lineup
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_id BIGINT                                  NOT NULL,
    team_id    BIGINT                                  NOT NULL,
    formation  VARCHAR(255),
    CONSTRAINT pk_matchlineup PRIMARY KEY (id)
);

CREATE TABLE match_player
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_lineup_id            BIGINT,
    player_statistics_id       BIGINT,
    player_id                  BIGINT,
    temporary_id               UUID,
    unregistered_player_name   VARCHAR(255),
    unregistered_player_number INTEGER,
    position                   VARCHAR(255),
    grid                       VARCHAR(255),
    substitute                 BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_matchplayer PRIMARY KEY (id)
);

CREATE TABLE player
(
    id             BIGINT       NOT NULL,
    name           VARCHAR(255) NOT NULL,
    korean_name    VARCHAR(255),
    photo_url      VARCHAR(255),
    position       VARCHAR(255),
    number         INTEGER,
    prevent_unlink BOOLEAN      NOT NULL,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE player_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_core_id BIGINT,
    api_id         BIGINT,
    name           VARCHAR(255),
    firstname      VARCHAR(255),
    lastname       VARCHAR(255),
    age            INTEGER,
    birth_date     date,
    birth_place    VARCHAR(255),
    birth_country  VARCHAR(255),
    nationality    VARCHAR(255),
    height         VARCHAR(255),
    weight         VARCHAR(255),
    number         INTEGER,
    position       VARCHAR(255),
    photo          VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_player_apisports PRIMARY KEY (id)
);

CREATE TABLE player_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    firstname      VARCHAR(255),
    lastname       VARCHAR(255),
    age            INTEGER,
    nationality    VARCHAR(255),
    position       VARCHAR(255),
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_player_core PRIMARY KEY (id)
);

CREATE TABLE player_statistics
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    minutes_played    INTEGER,
    position          VARCHAR(255),
    rating            VARCHAR(255),
    captain           BOOLEAN,
    substitute        BOOLEAN,
    shots_total       INTEGER,
    shots_on          INTEGER,
    goals             INTEGER,
    goals_conceded    INTEGER,
    assists           INTEGER,
    saves             INTEGER,
    passes_total      INTEGER,
    passes_key        INTEGER,
    passes_accuracy   INTEGER,
    tackles_total     INTEGER,
    interceptions     INTEGER,
    duels_total       INTEGER,
    duels_won         INTEGER,
    dribbles_attempts INTEGER,
    dribbles_success  INTEGER,
    fouls_committed   INTEGER,
    fouls_drawn       INTEGER,
    yellow_cards      INTEGER,
    red_cards         INTEGER,
    penalties_scored  INTEGER,
    penalties_missed  INTEGER,
    penalties_saved   INTEGER,
    CONSTRAINT pk_playerstatistics PRIMARY KEY (id)
);

CREATE TABLE preference_keys
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    user_id       BIGINT                                  NOT NULL,
    keyhash       VARCHAR(255)                            NOT NULL,
    enabled       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_preference_keys PRIMARY KEY (id)
);

CREATE TABLE standing
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    league_id     BIGINT,
    season        INTEGER                                 NOT NULL,
    CONSTRAINT pk_standing PRIMARY KEY (id)
);

CREATE TABLE standing_team
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    modified_date      TIMESTAMP WITHOUT TIME ZONE,
    team_id            BIGINT                                  NOT NULL,
    standing_id        BIGINT                                  NOT NULL,
    rank               INTEGER                                 NOT NULL,
    points             INTEGER                                 NOT NULL,
    goals_diff         INTEGER,
    group_name         VARCHAR(255),
    form               VARCHAR(255),
    description        VARCHAR(255),
    status             VARCHAR(255),
    all_played         INTEGER,
    all_win            INTEGER,
    all_draw           INTEGER,
    all_lose           INTEGER,
    all_goals_for      INTEGER,
    all_goals_against  INTEGER,
    home_played        INTEGER,
    home_win           INTEGER,
    home_draw          INTEGER,
    home_lose          INTEGER,
    home_goals_for     INTEGER,
    home_goals_against INTEGER,
    away_played        INTEGER,
    away_win           INTEGER,
    away_draw          INTEGER,
    away_lose          INTEGER,
    away_goals_for     INTEGER,
    away_goals_against INTEGER,
    CONSTRAINT pk_standing_team PRIMARY KEY (id)
);

CREATE TABLE team_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_core_id   BIGINT,
    venue_id       BIGINT,
    api_id         BIGINT,
    name           VARCHAR(255),
    code           VARCHAR(255),
    country        VARCHAR(255),
    founded        INTEGER,
    national       BOOLEAN,
    logo           VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_team_apisports PRIMARY KEY (id)
);

CREATE TABLE team_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    code           VARCHAR(255),
    country        VARCHAR(255),
    founded        INTEGER,
    national       BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_team_core PRIMARY KEY (id)
);

CREATE TABLE team_player
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_id   BIGINT,
    player_id BIGINT,
    CONSTRAINT pk_teamplayer PRIMARY KEY (id)
);

CREATE TABLE team_player_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_core_id   BIGINT                                  NOT NULL,
    player_core_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_team_player_core PRIMARY KEY (id)
);

CREATE TABLE team_statistics
(
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_id                 BIGINT                                  NOT NULL,
    team_id                    BIGINT                                  NOT NULL,
    shots_on_goal              INTEGER,
    shots_off_goal             INTEGER,
    total_shots                INTEGER,
    blocked_shots              INTEGER,
    shots_inside_box           INTEGER,
    shots_outside_box          INTEGER,
    fouls                      INTEGER,
    corner_kicks               INTEGER,
    offsides                   INTEGER,
    ball_possession            INTEGER,
    yellow_cards               INTEGER,
    red_cards                  INTEGER,
    goalkeeper_saves           INTEGER,
    total_passes               INTEGER,
    passes_accurate            INTEGER,
    passes_accuracy_percentage INTEGER,
    goals_prevented            INTEGER,
    CONSTRAINT pk_teamstatistics PRIMARY KEY (id)
);

CREATE TABLE teams
(
    id          BIGINT       NOT NULL,
    name        VARCHAR(255) NOT NULL,
    korean_name VARCHAR(255),
    logo        VARCHAR(255),
    CONSTRAINT pk_teams PRIMARY KEY (id)
);

CREATE TABLE user_file_paths
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            BIGINT                                  NOT NULL,
    domain             VARCHAR(255)                            NOT NULL,
    prefix_path        VARCHAR(255)                            NOT NULL,
    suffix_path        VARCHAR(255)                            NOT NULL,
    user_path_hash     VARCHAR(255)                            NOT NULL,
    user_path_category VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_user_file_paths PRIMARY KEY (id)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    username      VARCHAR(50)                             NOT NULL,
    nickname      VARCHAR(30),
    profile_image VARCHAR(255),
    password      VARCHAR(500)                            NOT NULL,
    enabled       BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE venue_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_id         BIGINT,
    name           VARCHAR(255),
    address        VARCHAR(255),
    city           VARCHAR(255),
    capacity       INTEGER,
    surface        VARCHAR(255),
    image          VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_venue_apisports PRIMARY KEY (id)
);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT uc_1281198db60fc46c49bb6f938 UNIQUE (match_player_uid);

ALTER TABLE authorities
    ADD CONSTRAINT uc_1b65235f41e7266b9a863b3fa UNIQUE (user_id, authority);

ALTER TABLE apisports_match_team_xg
    ADD CONSTRAINT uc_4dd204ea049b749660341f7ec UNIQUE (match_team_statistics_id, elapsed_time);

ALTER TABLE league_team
    ADD CONSTRAINT uc_8302529129b78279e1fb973cc UNIQUE (league_id, team_id);

ALTER TABLE apisports_match_player_stat
    ADD CONSTRAINT uc_apisports_match_player_stat_match_player UNIQUE (match_player_id);

ALTER TABLE team_player
    ADD CONSTRAINT uc_be62383aa4b4b52cbc6777301 UNIQUE (team_id, player_id);

ALTER TABLE fixture_core
    ADD CONSTRAINT uc_fixture_core_uid UNIQUE (uid);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_api UNIQUE (api_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_away_team UNIQUE (away_team_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_fixture_core UNIQUE (fixture_core_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_home_team UNIQUE (home_team_id);

ALTER TABLE fixtures
    ADD CONSTRAINT uc_fixtures_live_status UNIQUE (live_status_id);

ALTER TABLE league_apisports
    ADD CONSTRAINT uc_league_apisports_apiid UNIQUE (api_id);

ALTER TABLE league_apisports
    ADD CONSTRAINT uc_league_apisports_league_core UNIQUE (league_core_id);

ALTER TABLE league_core
    ADD CONSTRAINT uc_league_core_uid UNIQUE (uid);

ALTER TABLE match_player
    ADD CONSTRAINT uc_matchplayer_player_statistics UNIQUE (player_statistics_id);

ALTER TABLE player_apisports
    ADD CONSTRAINT uc_player_apisports_player_core UNIQUE (player_core_id);

ALTER TABLE player_core
    ADD CONSTRAINT uc_player_core_uid UNIQUE (uid);

ALTER TABLE preference_keys
    ADD CONSTRAINT uc_preference_keys_keyhash UNIQUE (keyhash);

ALTER TABLE preference_keys
    ADD CONSTRAINT uc_preference_keys_user UNIQUE (user_id);

ALTER TABLE team_apisports
    ADD CONSTRAINT uc_team_apisports_team_core UNIQUE (team_core_id);

ALTER TABLE team_core
    ADD CONSTRAINT uc_team_core_uid UNIQUE (uid);

ALTER TABLE user_file_paths
    ADD CONSTRAINT uc_user_file_paths_userpathhash UNIQUE (user_path_hash);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE league_team_core
    ADD CONSTRAINT uk_league_team UNIQUE (league_core_id, team_core_id);

CREATE INDEX idx_preference_player_active ON custom_player_photos (preference_key_id, player_id);

ALTER TABLE anonymous_users
    ADD CONSTRAINT FK_ANONYMOUS_USERS_ON_AUTOREMOTEGROUPID FOREIGN KEY (auto_remote_group_id) REFERENCES auto_remote_group (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_ASSIST FOREIGN KEY (assist_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_FIXTURE_API FOREIGN KEY (fixture_api_id) REFERENCES fixture_api_sports (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_MATCH_TEAM FOREIGN KEY (match_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_PLAYER FOREIGN KEY (player_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_ON_MATCH_TEAM FOREIGN KEY (match_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_ON_PLAYER_APISPORTS FOREIGN KEY (player_apisports_id) REFERENCES player_apisports (id);

ALTER TABLE apisports_match_player_stat
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_STAT_ON_MATCH_PLAYER FOREIGN KEY (match_player_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_team
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_ON_TEAMSTATISTICS FOREIGN KEY (team_statistics_id) REFERENCES apisports_match_team_stat (id);

ALTER TABLE apisports_match_team
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_ON_TEAM_APISPORTS FOREIGN KEY (team_apisports_id) REFERENCES team_apisports (id);

ALTER TABLE apisports_match_team_xg
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_XG_ON_MATCH_TEAM_STATISTICS FOREIGN KEY (match_team_statistics_id) REFERENCES apisports_match_team_stat (id);

ALTER TABLE authorities
    ADD CONSTRAINT FK_AUTHORITIES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE custom_player_photos
    ADD CONSTRAINT FK_CUSTOM_PLAYER_PHOTOS_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE custom_player_photos
    ADD CONSTRAINT FK_CUSTOM_PLAYER_PHOTOS_ON_PREFERENCE_KEY FOREIGN KEY (preference_key_id) REFERENCES preference_keys (id);

ALTER TABLE custom_player_photos
    ADD CONSTRAINT FK_CUSTOM_PLAYER_PHOTOS_ON_USER_FILE_PATH FOREIGN KEY (user_file_path_id) REFERENCES user_file_paths (id);

ALTER TABLE expected_goals
    ADD CONSTRAINT FK_EXPECTEDGOALS_ON_TEAM_STATISTICS FOREIGN KEY (team_statistics_id) REFERENCES team_statistics (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_AWAY_TEAM FOREIGN KEY (away_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_FIXTURE_CORE FOREIGN KEY (fixture_core_id) REFERENCES fixture_core (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_HOME_TEAM FOREIGN KEY (home_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_SEASON FOREIGN KEY (season_id) REFERENCES league_apisports_season (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venue_apisports (id);

ALTER TABLE fixture_event
    ADD CONSTRAINT FK_FIXTUREEVENT_ON_FIXTURE FOREIGN KEY (fixture_id) REFERENCES fixtures (fixture_id);

ALTER TABLE fixture_event
    ADD CONSTRAINT FK_FIXTUREEVENT_ON_MATCH_PLAYER FOREIGN KEY (match_player_id) REFERENCES match_player (id);

ALTER TABLE fixture_event
    ADD CONSTRAINT FK_FIXTUREEVENT_ON_MATCH_PLAYER_ASSIST FOREIGN KEY (match_player_assist_id) REFERENCES match_player (id);

ALTER TABLE fixture_event
    ADD CONSTRAINT FK_FIXTUREEVENT_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE fixtures
    ADD CONSTRAINT FK_FIXTURES_ON_AWAY_TEAM FOREIGN KEY (away_team_id) REFERENCES teams (id);

ALTER TABLE fixtures
    ADD CONSTRAINT FK_FIXTURES_ON_HOME_TEAM FOREIGN KEY (home_team_id) REFERENCES teams (id);

ALTER TABLE fixtures
    ADD CONSTRAINT FK_FIXTURES_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (league_id);

ALTER TABLE fixtures
    ADD CONSTRAINT FK_FIXTURES_ON_LIVE_STATUS FOREIGN KEY (live_status_id) REFERENCES live_status (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_AWAYTEAM FOREIGN KEY (away_team_id) REFERENCES team_core (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_HOMETEAM FOREIGN KEY (home_team_id) REFERENCES team_core (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES league_core (id);

ALTER TABLE league_team
    ADD CONSTRAINT FK_LEAGUETEAM_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (league_id);

ALTER TABLE league_team
    ADD CONSTRAINT FK_LEAGUETEAM_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE league_apisports
    ADD CONSTRAINT FK_LEAGUE_APISPORTS_ON_LEAGUE_CORE FOREIGN KEY (league_core_id) REFERENCES league_core (id);

ALTER TABLE league_apisports_season
    ADD CONSTRAINT FK_LEAGUE_APISPORTS_SEASON_ON_LEAGUE_APISPORTS FOREIGN KEY (league_apisports_id) REFERENCES league_apisports (id);

ALTER TABLE league_team_core
    ADD CONSTRAINT FK_LEAGUE_TEAM_CORE_ON_LEAGUE_CORE FOREIGN KEY (league_core_id) REFERENCES league_core (id);

ALTER TABLE league_team_core
    ADD CONSTRAINT FK_LEAGUE_TEAM_CORE_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE match_lineup
    ADD CONSTRAINT FK_MATCHLINEUP_ON_FIXTURE FOREIGN KEY (fixture_id) REFERENCES fixtures (fixture_id);

ALTER TABLE match_lineup
    ADD CONSTRAINT FK_MATCHLINEUP_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE match_player
    ADD CONSTRAINT FK_MATCHPLAYER_ON_MATCH_LINEUP FOREIGN KEY (match_lineup_id) REFERENCES match_lineup (id);

ALTER TABLE match_player
    ADD CONSTRAINT FK_MATCHPLAYER_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE match_player
    ADD CONSTRAINT FK_MATCHPLAYER_ON_PLAYER_STATISTICS FOREIGN KEY (player_statistics_id) REFERENCES player_statistics (id);

ALTER TABLE player_apisports
    ADD CONSTRAINT FK_PLAYER_APISPORTS_ON_PLAYER_CORE FOREIGN KEY (player_core_id) REFERENCES player_core (id);

ALTER TABLE preference_keys
    ADD CONSTRAINT FK_PREFERENCE_KEYS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE standing
    ADD CONSTRAINT FK_STANDING_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (league_id);

ALTER TABLE standing_team
    ADD CONSTRAINT FK_STANDING_TEAM_ON_STANDING FOREIGN KEY (standing_id) REFERENCES standing (id);

ALTER TABLE standing_team
    ADD CONSTRAINT FK_STANDING_TEAM_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_player
    ADD CONSTRAINT FK_TEAMPLAYER_ON_PLAYER FOREIGN KEY (player_id) REFERENCES player (id);

ALTER TABLE team_player
    ADD CONSTRAINT FK_TEAMPLAYER_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_statistics
    ADD CONSTRAINT FK_TEAMSTATISTICS_ON_FIXTURE FOREIGN KEY (fixture_id) REFERENCES fixtures (fixture_id);

ALTER TABLE team_statistics
    ADD CONSTRAINT FK_TEAMSTATISTICS_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_apisports
    ADD CONSTRAINT FK_TEAM_APISPORTS_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE team_apisports
    ADD CONSTRAINT FK_TEAM_APISPORTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venue_apisports (id);

ALTER TABLE team_player_core
    ADD CONSTRAINT FK_TEAM_PLAYER_CORE_ON_PLAYER_CORE FOREIGN KEY (player_core_id) REFERENCES player_core (id);

ALTER TABLE team_player_core
    ADD CONSTRAINT FK_TEAM_PLAYER_CORE_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE user_file_paths
    ADD CONSTRAINT FK_USER_FILE_PATHS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);