CREATE TABLE mock_backbone_league
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mock_uid       VARCHAR(255)                            NOT NULL,
    league_core_id BIGINT                                  NOT NULL,
    scenario_uid   VARCHAR(255),
    scenario_name  VARCHAR(255),
    created_at     TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_mock_backbone_league PRIMARY KEY (id)
);

ALTER TABLE mock_backbone_league
    ADD CONSTRAINT uc_mock_backbone_league_mock_uid UNIQUE (mock_uid);

ALTER TABLE mock_backbone_league
    ADD CONSTRAINT uc_mock_backbone_league_core UNIQUE (league_core_id);

CREATE INDEX idx_mock_league_core_id
    ON mock_backbone_league (league_core_id);

CREATE INDEX idx_mock_league_scenario_uid
    ON mock_backbone_league (scenario_uid);

CREATE INDEX idx_mock_league_created_at
    ON mock_backbone_league (created_at);

ALTER TABLE mock_backbone_league
    ADD CONSTRAINT fk_mock_league_on_league_core FOREIGN KEY (league_core_id) REFERENCES league_core (id);

CREATE TABLE mock_backbone_team
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mock_uid      VARCHAR(255)                            NOT NULL,
    team_core_id  BIGINT                                  NOT NULL,
    scenario_uid  VARCHAR(255),
    scenario_name VARCHAR(255),
    created_at    TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_mock_backbone_team PRIMARY KEY (id)
);

ALTER TABLE mock_backbone_team
    ADD CONSTRAINT uc_mock_backbone_team_mock_uid UNIQUE (mock_uid);

ALTER TABLE mock_backbone_team
    ADD CONSTRAINT uc_mock_backbone_team_core UNIQUE (team_core_id);

CREATE INDEX idx_mock_team_core_id
    ON mock_backbone_team (team_core_id);

CREATE INDEX idx_mock_team_scenario_uid
    ON mock_backbone_team (scenario_uid);

CREATE INDEX idx_mock_team_created_at
    ON mock_backbone_team (created_at);

ALTER TABLE mock_backbone_team
    ADD CONSTRAINT fk_mock_team_on_team_core FOREIGN KEY (team_core_id) REFERENCES team_core (id);

CREATE TABLE mock_backbone_fixture
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mock_uid            VARCHAR(255)                            NOT NULL,
    fixture_core_id     BIGINT                                  NOT NULL,
    initial_status_code VARCHAR(255)                            NOT NULL,
    initial_kickoff     TIMESTAMP WITH TIME ZONE,
    scenario_uid        VARCHAR(255),
    scenario_name       VARCHAR(255),
    created_at          TIMESTAMP WITH TIME ZONE                NOT NULL,
    CONSTRAINT pk_mock_backbone_fixture PRIMARY KEY (id)
);

ALTER TABLE mock_backbone_fixture
    ADD CONSTRAINT uc_mock_backbone_fixture_mock_uid UNIQUE (mock_uid);

ALTER TABLE mock_backbone_fixture
    ADD CONSTRAINT uc_mock_backbone_fixture_core UNIQUE (fixture_core_id);

CREATE INDEX idx_mock_fixture_core_id
    ON mock_backbone_fixture (fixture_core_id);

CREATE INDEX idx_mock_fixture_scenario_uid
    ON mock_backbone_fixture (scenario_uid);

CREATE INDEX idx_mock_fixture_created_at
    ON mock_backbone_fixture (created_at);

ALTER TABLE mock_backbone_fixture
    ADD CONSTRAINT fk_mock_fixture_on_fixture_core FOREIGN KEY (fixture_core_id) REFERENCES fixture_core (id);
