CREATE TABLE apisports_match_event
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_api_id BIGINT,
    match_team_id  BIGINT,
    player_id      BIGINT,
    assist_id      BIGINT,
    sequence       INTEGER                                 NOT NULL,
    elapsed_time   INTEGER,
    extra_time     INTEGER,
    event_type     VARCHAR(255),
    detail         VARCHAR(255),
    comments       VARCHAR(255),
    CONSTRAINT pk_apisports_match_event PRIMARY KEY (id)
);

CREATE TABLE apisports_match_player
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_uid    VARCHAR(255)                            NOT NULL,
    player_apisports_id BIGINT,
    name                VARCHAR(255)                            NOT NULL,
    number              INTEGER,
    position            VARCHAR(255)                            NOT NULL,
    grid                VARCHAR(255),
    substitute          BOOLEAN                                 NOT NULL,
    match_team_id       BIGINT,
    CONSTRAINT pk_apisports_match_player PRIMARY KEY (id)
);

CREATE TABLE apisports_match_player_stat
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_player_id   BIGINT,
    minutes_played    INTEGER,
    shirt_number      INTEGER,
    position          VARCHAR(255),
    rating            DOUBLE PRECISION,
    is_captain        BOOLEAN,
    is_substitute     BOOLEAN,
    offsides          INTEGER,
    shots_total       INTEGER,
    shots_on_target   INTEGER,
    goals_total       INTEGER,
    goals_conceded    INTEGER,
    assists           INTEGER,
    saves             INTEGER,
    passes_total      INTEGER,
    key_passes        INTEGER,
    passes_accuracy   INTEGER,
    tackles_total     INTEGER,
    blocks            INTEGER,
    interceptions     INTEGER,
    duels_total       INTEGER,
    duels_won         INTEGER,
    dribbles_attempts INTEGER,
    dribbles_success  INTEGER,
    dribbles_past     INTEGER,
    fouls_drawn       INTEGER,
    fouls_committed   INTEGER,
    yellow_cards      INTEGER,
    red_cards         INTEGER,
    penalty_won       INTEGER,
    penalty_committed INTEGER,
    penalty_scored    INTEGER,
    penalty_missed    INTEGER,
    penalty_saved     INTEGER,
    CONSTRAINT pk_apisports_match_player_stat PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_apisports_id        BIGINT,
    formation                VARCHAR(255),
    winner                   BOOLEAN,
    team_statistics_id       BIGINT,
    player_color_primary     VARCHAR(255),
    player_color_number      VARCHAR(255),
    player_color_border      VARCHAR(255),
    goalkeeper_color_primary VARCHAR(255),
    goalkeeper_color_number  VARCHAR(255),
    goalkeeper_color_border  VARCHAR(255),
    CONSTRAINT pk_apisports_match_team PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team_stat
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    shots_on_goal     INTEGER,
    shots_off_goal    INTEGER,
    total_shots       INTEGER,
    blocked_shots     INTEGER,
    shots_inside_box  INTEGER,
    shots_outside_box INTEGER,
    fouls             INTEGER,
    corner_kicks      INTEGER,
    offsides          INTEGER,
    ball_possession   VARCHAR(255),
    yellow_cards      INTEGER,
    red_cards         INTEGER,
    goalkeeper_saves  INTEGER,
    total_passes      INTEGER,
    passes_accurate   INTEGER,
    passes_percentage VARCHAR(255),
    goals_prevented   INTEGER,
    CONSTRAINT pk_apisports_match_team_stat PRIMARY KEY (id)
);

CREATE TABLE apisports_match_team_xg
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    match_team_statistics_id BIGINT                                  NOT NULL,
    elapsed_time             INTEGER                                 NOT NULL,
    expected_goals           DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_apisports_match_team_xg PRIMARY KEY (id)
);

CREATE TABLE fixture_api_sports
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_core_id BIGINT,
    api_id          BIGINT                                  NOT NULL,
    referee         VARCHAR(255),
    date            TIMESTAMP WITH TIME ZONE,
    round           VARCHAR(255),
    prevent_update  BOOLEAN                                 NOT NULL,
    available       BOOLEAN                                 NOT NULL,
    venue_id        BIGINT,
    season_id       BIGINT,
    home_team_id    BIGINT,
    away_team_id    BIGINT,
    long_status     VARCHAR(255),
    short_status    VARCHAR(255),
    elapsed         INTEGER,
    extra           INTEGER,
    total_home      INTEGER,
    total_away      INTEGER,
    halftime_home   INTEGER,
    halftime_away   INTEGER,
    fulltime_home   INTEGER,
    fulltime_away   INTEGER,
    extratime_home  INTEGER,
    extratime_away  INTEGER,
    penalty_home    INTEGER,
    penalty_away    INTEGER,
    CONSTRAINT pk_fixtureapisports PRIMARY KEY (id)
);

CREATE TABLE fixture_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    kickoff        TIMESTAMP WITH TIME ZONE,
    status_text    VARCHAR(255),
    status_code    VARCHAR(255),
    elapsed_min    INTEGER,
    league_id      BIGINT,
    home_team_id   BIGINT,
    away_team_id   BIGINT,
    goals_home     INTEGER,
    goals_away     INTEGER,
    finished       BOOLEAN                                 NOT NULL,
    available      BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_fixture_core PRIMARY KEY (id)
);

CREATE TABLE league_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_id BIGINT,
    api_id         BIGINT                                  NOT NULL,
    name           VARCHAR(255),
    type           VARCHAR(255),
    logo           VARCHAR(255),
    country_name   VARCHAR(255),
    country_code   VARCHAR(255),
    country_flag   VARCHAR(255),
    current_season INTEGER,
    available      BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_league_apisports PRIMARY KEY (id)
);

CREATE TABLE league_apisports_season
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    season_year         INTEGER,
    season_start        date,
    season_end          date,
    league_apisports_id BIGINT,
    fixtures_events     BOOLEAN,
    fixtures_lineups    BOOLEAN,
    fixtures_statistics BOOLEAN,
    fixtures_players    BOOLEAN,
    standings           BOOLEAN,
    players             BOOLEAN,
    top_scorers         BOOLEAN,
    top_assists         BOOLEAN,
    top_cards           BOOLEAN,
    injuries            BOOLEAN,
    predictions         BOOLEAN,
    odds                BOOLEAN,
    CONSTRAINT pk_league_apisports_season PRIMARY KEY (id)
);

CREATE TABLE league_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    available      BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_league_core PRIMARY KEY (id)
);

CREATE TABLE league_team_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_id BIGINT                                  NOT NULL,
    team_core_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_league_team_core PRIMARY KEY (id)
);

CREATE TABLE player_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    player_core_id BIGINT,
    api_id         BIGINT,
    name           VARCHAR(255),
    firstname      VARCHAR(255),
    lastname       VARCHAR(255),
    age            INTEGER,
    birth_date     date,
    birth_place    VARCHAR(255),
    birth_country  VARCHAR(255),
    nationality    VARCHAR(255),
    height         VARCHAR(255),
    weight         VARCHAR(255),
    number         INTEGER,
    position       VARCHAR(255),
    photo          VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_player_apisports PRIMARY KEY (id)
);

CREATE TABLE player_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    firstname      VARCHAR(255),
    lastname       VARCHAR(255),
    age            INTEGER,
    nationality    VARCHAR(255),
    position       VARCHAR(255),
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_player_core PRIMARY KEY (id)
);

CREATE TABLE standing
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date  TIMESTAMP WITHOUT TIME ZONE,
    modified_date TIMESTAMP WITHOUT TIME ZONE,
    league_id     BIGINT,
    season        INTEGER                                 NOT NULL,
    CONSTRAINT pk_standing PRIMARY KEY (id)
);

CREATE TABLE standing_team
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    modified_date      TIMESTAMP WITHOUT TIME ZONE,
    team_id            BIGINT                                  NOT NULL,
    standing_id        BIGINT                                  NOT NULL,
    rank               INTEGER                                 NOT NULL,
    points             INTEGER                                 NOT NULL,
    goals_diff         INTEGER,
    group_name         VARCHAR(255),
    form               VARCHAR(255),
    description        VARCHAR(255),
    status             VARCHAR(255),
    all_played         INTEGER,
    all_win            INTEGER,
    all_draw           INTEGER,
    all_lose           INTEGER,
    all_goals_for      INTEGER,
    all_goals_against  INTEGER,
    home_played        INTEGER,
    home_win           INTEGER,
    home_draw          INTEGER,
    home_lose          INTEGER,
    home_goals_for     INTEGER,
    home_goals_against INTEGER,
    away_played        INTEGER,
    away_win           INTEGER,
    away_draw          INTEGER,
    away_lose          INTEGER,
    away_goals_for     INTEGER,
    away_goals_against INTEGER,
    CONSTRAINT pk_standing_team PRIMARY KEY (id)
);

CREATE TABLE team_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_core_id   BIGINT,
    venue_id       BIGINT,
    api_id         BIGINT,
    name           VARCHAR(255),
    code           VARCHAR(255),
    country        VARCHAR(255),
    founded        INTEGER,
    national       BOOLEAN,
    logo           VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_team_apisports PRIMARY KEY (id)
);

CREATE TABLE team_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uid            VARCHAR(255)                            NOT NULL,
    name           VARCHAR(255)                            NOT NULL,
    name_ko        VARCHAR(255),
    code           VARCHAR(255),
    country        VARCHAR(255),
    founded        INTEGER,
    national       BOOLEAN                                 NOT NULL,
    auto_generated BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_team_core PRIMARY KEY (id)
);

CREATE TABLE team_player_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    team_core_id   BIGINT                                  NOT NULL,
    player_core_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_team_player_core PRIMARY KEY (id)
);

CREATE TABLE venue_apisports
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    api_id         BIGINT,
    name           VARCHAR(255),
    address        VARCHAR(255),
    city           VARCHAR(255),
    capacity       INTEGER,
    surface        VARCHAR(255),
    image          VARCHAR(255),
    prevent_update BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_venue_apisports PRIMARY KEY (id)
);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT uc_1281198db60fc46c49bb6f938 UNIQUE (match_player_uid);

ALTER TABLE apisports_match_team_xg
    ADD CONSTRAINT uc_4dd204ea049b749660341f7ec UNIQUE (match_team_statistics_id, elapsed_time);

ALTER TABLE apisports_match_player_stat
    ADD CONSTRAINT uc_apisports_match_player_stat_match_player UNIQUE (match_player_id);

ALTER TABLE fixture_core
    ADD CONSTRAINT uc_fixture_core_uid UNIQUE (uid);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_api UNIQUE (api_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_away_team UNIQUE (away_team_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_fixture_core UNIQUE (fixture_core_id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT uc_fixtureapisports_home_team UNIQUE (home_team_id);

ALTER TABLE fixtures
    ADD CONSTRAINT uc_fixtures_live_status UNIQUE (live_status_id);

ALTER TABLE league_apisports
    ADD CONSTRAINT uc_league_apisports_apiid UNIQUE (api_id);

ALTER TABLE league_apisports
    ADD CONSTRAINT uc_league_apisports_league_core UNIQUE (league_core_id);

ALTER TABLE league_core
    ADD CONSTRAINT uc_league_core_uid UNIQUE (uid);

ALTER TABLE match_player
    ADD CONSTRAINT uc_matchplayer_player_statistics UNIQUE (player_statistics_id);

ALTER TABLE player_apisports
    ADD CONSTRAINT uc_player_apisports_player_core UNIQUE (player_core_id);

ALTER TABLE player_core
    ADD CONSTRAINT uc_player_core_uid UNIQUE (uid);

ALTER TABLE preference_keys
    ADD CONSTRAINT uc_preference_keys_keyhash UNIQUE (keyhash);

ALTER TABLE preference_keys
    ADD CONSTRAINT uc_preference_keys_user UNIQUE (user_id);

ALTER TABLE team_apisports
    ADD CONSTRAINT uc_team_apisports_team_core UNIQUE (team_core_id);

ALTER TABLE team_core
    ADD CONSTRAINT uc_team_core_uid UNIQUE (uid);

ALTER TABLE user_file_paths
    ADD CONSTRAINT uc_user_file_paths_userpathhash UNIQUE (user_path_hash);

ALTER TABLE users
    ADD CONSTRAINT uc_users_nickname UNIQUE (nickname);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

ALTER TABLE league_team_core
    ADD CONSTRAINT uk_league_team UNIQUE (league_core_id, team_core_id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_ASSIST FOREIGN KEY (assist_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_FIXTURE_API FOREIGN KEY (fixture_api_id) REFERENCES fixture_api_sports (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_MATCH_TEAM FOREIGN KEY (match_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE apisports_match_event
    ADD CONSTRAINT FK_APISPORTS_MATCH_EVENT_ON_PLAYER FOREIGN KEY (player_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_ON_MATCH_TEAM FOREIGN KEY (match_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE apisports_match_player
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_ON_PLAYER_APISPORTS FOREIGN KEY (player_apisports_id) REFERENCES player_apisports (id);

ALTER TABLE apisports_match_player_stat
    ADD CONSTRAINT FK_APISPORTS_MATCH_PLAYER_STAT_ON_MATCH_PLAYER FOREIGN KEY (match_player_id) REFERENCES apisports_match_player (id);

ALTER TABLE apisports_match_team
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_ON_TEAMSTATISTICS FOREIGN KEY (team_statistics_id) REFERENCES apisports_match_team_stat (id);

ALTER TABLE apisports_match_team
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_ON_TEAM_APISPORTS FOREIGN KEY (team_apisports_id) REFERENCES team_apisports (id);

ALTER TABLE apisports_match_team_xg
    ADD CONSTRAINT FK_APISPORTS_MATCH_TEAM_XG_ON_MATCH_TEAM_STATISTICS FOREIGN KEY (match_team_statistics_id) REFERENCES apisports_match_team_stat (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_AWAY_TEAM FOREIGN KEY (away_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_FIXTURE_CORE FOREIGN KEY (fixture_core_id) REFERENCES fixture_core (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_HOME_TEAM FOREIGN KEY (home_team_id) REFERENCES apisports_match_team (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_SEASON FOREIGN KEY (season_id) REFERENCES league_apisports_season (id);

ALTER TABLE fixture_api_sports
    ADD CONSTRAINT FK_FIXTUREAPISPORTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venue_apisports (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_AWAYTEAM FOREIGN KEY (away_team_id) REFERENCES team_core (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_HOMETEAM FOREIGN KEY (home_team_id) REFERENCES team_core (id);

ALTER TABLE fixture_core
    ADD CONSTRAINT FK_FIXTURE_CORE_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES league_core (id);

ALTER TABLE league_apisports
    ADD CONSTRAINT FK_LEAGUE_APISPORTS_ON_LEAGUE_CORE FOREIGN KEY (league_core_id) REFERENCES league_core (id);

ALTER TABLE league_apisports_season
    ADD CONSTRAINT FK_LEAGUE_APISPORTS_SEASON_ON_LEAGUE_APISPORTS FOREIGN KEY (league_apisports_id) REFERENCES league_apisports (id);

ALTER TABLE league_team_core
    ADD CONSTRAINT FK_LEAGUE_TEAM_CORE_ON_LEAGUE_CORE FOREIGN KEY (league_core_id) REFERENCES league_core (id);

ALTER TABLE league_team_core
    ADD CONSTRAINT FK_LEAGUE_TEAM_CORE_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE player_apisports
    ADD CONSTRAINT FK_PLAYER_APISPORTS_ON_PLAYER_CORE FOREIGN KEY (player_core_id) REFERENCES player_core (id);

ALTER TABLE standing
    ADD CONSTRAINT FK_STANDING_ON_LEAGUE FOREIGN KEY (league_id) REFERENCES leagues (league_id);

ALTER TABLE standing_team
    ADD CONSTRAINT FK_STANDING_TEAM_ON_STANDING FOREIGN KEY (standing_id) REFERENCES standing (id);

ALTER TABLE standing_team
    ADD CONSTRAINT FK_STANDING_TEAM_ON_TEAM FOREIGN KEY (team_id) REFERENCES teams (id);

ALTER TABLE team_apisports
    ADD CONSTRAINT FK_TEAM_APISPORTS_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE team_apisports
    ADD CONSTRAINT FK_TEAM_APISPORTS_ON_VENUE FOREIGN KEY (venue_id) REFERENCES venue_apisports (id);

ALTER TABLE team_player_core
    ADD CONSTRAINT FK_TEAM_PLAYER_CORE_ON_PLAYER_CORE FOREIGN KEY (player_core_id) REFERENCES player_core (id);

ALTER TABLE team_player_core
    ADD CONSTRAINT FK_TEAM_PLAYER_CORE_ON_TEAM_CORE FOREIGN KEY (team_core_id) REFERENCES team_core (id);

ALTER TABLE player_statistics
    DROP COLUMN fixture_id;

ALTER TABLE player_statistics
    DROP COLUMN player_id;

ALTER TABLE player_statistics
    DROP COLUMN team_id;

ALTER TABLE last_cache_log
    ALTER COLUMN api_cache_type TYPE VARCHAR(255) USING (api_cache_type::VARCHAR(255));

ALTER TABLE authorities
    ALTER COLUMN authority TYPE VARCHAR(50) USING (authority::VARCHAR(50));

ALTER TABLE auto_remote_group
    ALTER COLUMN expired_at SET NOT NULL;

ALTER TABLE auto_remote_group
    ALTER COLUMN last_active_at SET NOT NULL;

ALTER TABLE anonymous_users
    ALTER COLUMN last_connected_at SET NOT NULL;

ALTER TABLE fixture_event
    ALTER COLUMN team_id DROP NOT NULL;

ALTER TABLE fixture_event
    ALTER COLUMN type TYPE VARCHAR(255) USING (type::VARCHAR(255));

ALTER TABLE user_file_paths
    ALTER COLUMN user_path_category TYPE VARCHAR(255) USING (user_path_category::VARCHAR(255));