CREATE TABLE fixture_match_collect_state
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fixture_core_id      BIGINT                                  NOT NULL,
    match_collect_status VARCHAR(64)                             NOT NULL DEFAULT 'PENDING',
    last_collected_at    TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_fixture_match_collect_state PRIMARY KEY (id),
    CONSTRAINT uc_fixture_match_collect_state_fixture UNIQUE (fixture_core_id),
    CONSTRAINT fk_fixture_match_collect_state_fixture FOREIGN KEY (fixture_core_id) REFERENCES fixture_core (id)
);

CREATE INDEX idx_match_collect_status_collected
    ON fixture_match_collect_state (match_collect_status, last_collected_at);

CREATE INDEX idx_fixture_core_match_collect_scan
    ON fixture_core (available, kickoff, league_id);
