CREATE TABLE league_season_core
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    league_core_id BIGINT                                  NOT NULL,
    season_year    INTEGER                                 NOT NULL,
    season_start   date,
    season_end     date,
    current        BOOLEAN                                 NOT NULL DEFAULT FALSE,
    auto_generated BOOLEAN                                 NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_league_season_core PRIMARY KEY (id),
    CONSTRAINT uc_league_season_core_league_year UNIQUE (league_core_id, season_year),
    CONSTRAINT fk_league_season_core_on_league_core FOREIGN KEY (league_core_id) REFERENCES league_core (id)
);

CREATE INDEX idx_league_season_core_league_current
    ON league_season_core (league_core_id, current);
